/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@class VGLContext;

@interface VGLShader : NSObject {
    VGLContext *context;
    int token;
}

@property VGLContext * context;
@property(readonly) int token;

- (id)context;
- (void)dealloc;
- (id)initWithName:(id)arg1 shaderType:(unsigned int)arg2;
- (void)printShaderInfoLog;
- (void)setContext:(id)arg1;
- (BOOL)status:(unsigned int)arg1;
- (int)token;

@end
