/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKAccountWebServicePhysicalCardActionRequest : PKAccountWebServiceRequest <NSSecureCoding, PKAccountWebServiceApplePayTrustProtocol> {
    NSString * _accountIdentifier;
    PKPhysicalCardAction * _action;
    PKPaymentDeviceMetadata * _deviceMetadata;
    NSString * _physicalCardIdentifier;
    NSData * _publicKeyHash;
    NSURL * baseURL;
    PKApplePayTrustHashResponse * hashResponse;
}

@property (nonatomic, copy) NSString *accountIdentifier;
@property (nonatomic, retain) PKPhysicalCardAction *action;
@property (nonatomic, retain) NSURL *baseURL;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) PKPaymentDeviceMetadata *deviceMetadata;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) PKApplePayTrustHashResponse *hashResponse;
@property (nonatomic, copy) NSString *physicalCardIdentifier;
@property (nonatomic, copy) NSData *publicKeyHash;
@property (readonly) Class superclass;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_urlRequestWithAppleAccountInformation:(id)arg1;
- (id)accountIdentifier;
- (id)action;
- (id)baseURL;
- (id)deviceMetadata;
- (void)encodeWithCoder:(id)arg1;
- (id)endpointComponents;
- (id)hashResponse;
- (id)initWithCoder:(id)arg1;
- (id)manifestHashWithReferenceIdentifier:(id)arg1;
- (id)physicalCardIdentifier;
- (id)publicKeyHash;
- (void)setAccountIdentifier:(id)arg1;
- (void)setAction:(id)arg1;
- (void)setBaseURL:(id)arg1;
- (void)setDeviceMetadata:(id)arg1;
- (void)setHashResponse:(id)arg1;
- (void)setPhysicalCardIdentifier:(id)arg1;
- (void)setPublicKeyHash:(id)arg1;
- (Class)signatureResponseClass;

@end
