/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppLaunchStats.framework/AppLaunchStats
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class AppLaunchStatsSaveAndRestore, AppLaunchStatsState, BKSApplicationStateMonitor, NSMutableDictionary, NSMutableString, NSObject<OS_dispatch_queue>;

@interface AppLaunchStatsSBMonitor : NSObject <DuetLoggerProtocol, DuetSaveAndRestore> {
    BOOL _enableAppSwitcherCheck;
    BOOL _enableWasRecentlyLaunched;
    AppLaunchStatsState *aplsState;
    BKSApplicationStateMonitor *appStateMonitor;
    NSMutableDictionary *blackListed;
    id callback;
    NSMutableString *foreGroundApp;
    NSMutableDictionary *recentList;
    AppLaunchStatsSaveAndRestore *saveAndRestoreContext;
    NSObject<OS_dispatch_queue> *sbMonitorQueue;
    NSMutableDictionary *trendList;
}

@property(readonly) BOOL enableAppSwitcherCheck;
@property(readonly) BOOL enableWasRecentlyLaunched;
@property(readonly) NSMutableString * foreGroundApp;

- (void).cxx_destruct;
- (void)addToBlackList:(id)arg1;
- (void)appSuspendedTriggerExternalEvent:(id)arg1;
- (void)appSwitchedObserver:(id)arg1;
- (void)clearTrendingCache;
- (BOOL)enableAppSwitcherCheck;
- (BOOL)enableWasRecentlyLaunched;
- (id)foreGroundApp;
- (id)init:(id)arg1 withCallback:(id)arg2;
- (void)initListenerForAppStateChange;
- (bool)isForeGroundApp:(id)arg1;
- (bool)isRemovedFromAppSwitcher:(id)arg1;
- (void)logAll:(struct __asl_object_s { }*)arg1 withMsg:(struct __asl_object_s { }*)arg2 withLevel:(int)arg3;
- (void)logLight:(struct __asl_object_s { }*)arg1 withMsg:(struct __asl_object_s { }*)arg2 withLevel:(int)arg3;
- (void)reloadConfiguration;
- (void)removeFromBlackList:(id)arg1;
- (void)restore:(id)arg1;
- (void)save:(id)arg1;
- (void)saveContext:(id)arg1;
- (void)updateFGAppID:(id)arg1;
- (bool)wasRecentlyLaunched:(id)arg1;

@end
