/* Generated by RuntimeBrowser on iPhone OS 3.0
   Image: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@class NSArray;



@interface SUTouchCaptureView : UIControl 
{
    NSArray *_passThroughViews;
}

@property(retain) NSArray *passThroughViews; /* unknown property attribute: V_passThroughViews */


- (void)dealloc;
- (id)hitTest:(struct CGPoint { float x1; float x2; })arg1 withEvent:(id)arg2;
- (id)passThroughViews;
- (void)setPassThroughViews:(id)arg1;

@end
