/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

@interface CKDAggregateZonePCSOperation : CKDDatabaseOperation {
    BOOL  _isHandlingPCSOplockFailure;
    int  _maxZoneSaveAttempts;
    int  _numZoneSaveAttempts;
    NSArray * _sourceZoneIDs;
    CKRecordZone * _targetZone;
    NSMutableDictionary * _zonePCSDataByZoneID;
}

@property BOOL isHandlingPCSOplockFailure;
@property (nonatomic) int maxZoneSaveAttempts;
@property (nonatomic) int numZoneSaveAttempts;
@property (nonatomic, retain) NSArray *sourceZoneIDs;
@property (nonatomic, retain) CKRecordZone *targetZone;
@property (nonatomic, retain) NSMutableDictionary *zonePCSDataByZoneID;

- (void).cxx_destruct;
- (void)_fetchPCSDataForZoneID:(id)arg1;
- (void)_fetchZonePCS;
- (void)_handleZoneSavedWithID:(id)arg1 responseCode:(id)arg2;
- (void)_prepareTargetZonePCS;
- (BOOL)_saveTargetZone;
- (void)_setPermanentOplockFailure;
- (id)activityCreate;
- (id)initWithOperationInfo:(id)arg1 clientContext:(id)arg2;
- (BOOL)isHandlingPCSOplockFailure;
- (void)main;
- (BOOL)makeStateTransition;
- (int)maxZoneSaveAttempts;
- (id)nameForState:(unsigned int)arg1;
- (int)numZoneSaveAttempts;
- (void)setIsHandlingPCSOplockFailure:(BOOL)arg1;
- (void)setMaxZoneSaveAttempts:(int)arg1;
- (void)setNumZoneSaveAttempts:(int)arg1;
- (void)setSourceZoneIDs:(id)arg1;
- (void)setTargetZone:(id)arg1;
- (void)setZonePCSDataByZoneID:(id)arg1;
- (id)sourceZoneIDs;
- (id)targetZone;
- (id)zonePCSDataByZoneID;

@end
