/* Generated by RuntimeBrowser on iPhone OS 4.0
   Image: /System/Library/Frameworks/Foundation.framework/Foundation
 */



@interface NSCharacterSet : NSObject <NSCopying, NSMutableCopying, NSCoding>
{
}

+ (id)decomposableCharacterSet;
+ (id)punctuationCharacterSet;
+ (id)symbolCharacterSet;
+ (id)alphanumericCharacterSet;
+ (void)initialize;
+ (id)whitespaceCharacterSet;
+ (id)decimalDigitCharacterSet;
+ (id)characterSetWithCharactersInString:(id)arg1;
+ (id)whitespaceAndNewlineCharacterSet;
+ (id)characterSetWithRange:(struct _NSRange { NSUInteger x1; NSUInteger x2; })arg1;
+ (id)uppercaseLetterCharacterSet;
+ (id)controlCharacterSet;
+ (id)letterCharacterSet;
+ (id)lowercaseLetterCharacterSet;
+ (id)nonBaseCharacterSet;
+ (id)illegalCharacterSet;
+ (id)capitalizedLetterCharacterSet;
+ (id)newlineCharacterSet;
+ (id)characterSetWithBitmapRepresentation:(id)arg1;
+ (id)characterSetWithContentsOfFile:(id)arg1;
+ (id)CJKCharacterSet;
+ (id)whitespaceNewlineAndSpecialCharacterSet;
+ (id)wordBreakCharacterSet;

- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (BOOL)characterIsMember:(unsigned short)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)invertedSet;
- (NSUInteger)hash;
- (void)encodeWithCoder:(id)arg1;
- (NSUInteger)count;
- (id)init;
- (BOOL)isEqual:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEmpty;
- (BOOL)isSupersetOfSet:(id)arg1;
- (void)makeImmutable;
- (id)_retainedBitmapRepresentation;
- (BOOL)isMutable;
- (struct __CFCharacterSet { }*)_expandedCFCharacterSet;
- (BOOL)longCharacterIsMember:(unsigned long)arg1;
- (BOOL)hasMemberInPlane:(unsigned char)arg1;
- (id)bitmapRepresentation;
- (unsigned long)_cfTypeID;

@end
