/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@class NSObject<TSDContainerInfo>, TNPageController, TSDInfoGeometry, TSPObject<TSDOwningAttachment>;

@interface TNPageInfoContainer : NSObject <TSDContainerInfo> {
    TNPageController *_pageController;
    unsigned int _pageIndex;
}

@property(getter=isAnchoredToText,readonly) BOOL anchoredToText;
@property(getter=isAttachedToBodyText,readonly) BOOL attachedToBodyText;
@property(getter=isFloatingAboveText,readonly) BOOL floatingAboveText;
@property(copy) TSDInfoGeometry * geometry;
@property(getter=isInlineWithText,readonly) BOOL inlineWithText;
@property BOOL matchesObjectPlaceholderGeometry;
@property TSPObject<TSDOwningAttachment> * owningAttachment;
@property(readonly) TSPObject<TSDOwningAttachment> * owningAttachmentNoRecurse;
@property NSObject<TSDContainerInfo> * parentInfo;

- (id)childInfos;
- (id)copyWithContext:(id)arg1;
- (void)dealloc;
- (id)geometry;
- (id)initWithPageIndex:(unsigned int)arg1 pageController:(id)arg2;
- (BOOL)isAnchoredToText;
- (BOOL)isAttachedToBodyText;
- (BOOL)isFloatingAboveText;
- (BOOL)isInlineWithText;
- (BOOL)isThemeContent;
- (Class)layoutClass;
- (id)owningAttachment;
- (id)owningAttachmentNoRecurse;
- (id)pageController;
- (unsigned int)pageIndex;
- (id)parentInfo;
- (Class)repClass;
- (void)setGeometry:(id)arg1;
- (void)setOwningAttachment:(id)arg1;
- (void)setParentInfo:(id)arg1;

@end
