/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartFeatureMixed : TSCHChartFeatureCategory

- (id)defaultDataFileName;
- (id)genericToSpecificPropertyMap;
- (Class)presetImagerClass;
- (id)supportedAxisScales;
- (id)supportedSeriesTypes;
- (bool)supportsConnectingLines;
- (bool)supportsEditing;
- (bool)supportsGroupedShadows;
- (bool)supportsIndividualShadowRendering;
- (bool)supportsMultipleSeriesTypes;
- (bool)supportsSymbolOverhang;
- (id)userInterfaceName;
- (Class)valueAxisClassForID:(id)arg1 scale:(int)arg2;

@end
