/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCH3DFixedFunctionMaterialShaderEffect : TSCH3DMaterialShaderEffect

- (void)injectCommonShaderInto:(id)arg1 context:(id)arg2;

@end
