/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCNotificationListSection : NSObject <BSDescriptionProviding> {
    NSString * _identifier;
    NSMutableArray * _notificationRequests;
    NSString * _title;
}

@property (nonatomic, readonly) int count;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (nonatomic, readonly) NSString *identifier;
@property (nonatomic, retain) NSMutableArray *notificationRequests;
@property (nonatomic, retain) NSDate *sectionDate;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSString *title;

- (void).cxx_destruct;
- (unsigned int)_indexOfRequestMatchingRequest:(id)arg1;
- (unsigned int)_insertionIndexForNotificationRequest:(id)arg1;
- (id)_matchIdentifierForNotificationRequest:(id)arg1;
- (unsigned int)addNotificationRequest:(id)arg1;
- (id)allNotificationRequests;
- (BOOL)containsNotificationRequestMatchingRequest:(id)arg1;
- (int)count;
- (id)debugDescription;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)identifier;
- (int)indexForNotificationRequest:(id)arg1;
- (unsigned int)indexForNotificationRequestMatchingRequest:(id)arg1;
- (id)init;
- (id)initWithIdentifier:(id)arg1 title:(id)arg2;
- (unsigned int)insertionIndexForNotificationRequest:(id)arg1;
- (id)notificationRequestAtIndex:(unsigned int)arg1;
- (id)notificationRequests;
- (unsigned int)removeNotificationRequest:(id)arg1;
- (unsigned int)replaceNotificationRequest:(id)arg1;
- (id)sectionDate;
- (void)setNotificationRequests:(id)arg1;
- (void)setSectionDate:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)title;

@end
