/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
 */

@class NSInvocation, NSString;

@interface BBXPCOutgoingConnection : BBXPCConnection {
    BOOL _autoReconnect;
    NSInvocation *_connectionEstablishmentInvocation;
    NSString *_name;
}

@property BOOL autoReconnects;
@property(retain) NSInvocation * connectionEstablishmentInvocation;
@property(readonly) NSString * serviceName;

- (void)_configureRemoteProxy;
- (void)_connectionEstablishedResponse:(id)arg1;
- (id)_signatureForSelectorInRemoteProtocol:(SEL)arg1;
- (BOOL)autoReconnects;
- (id)connectionEstablishmentInvocation;
- (void)dealloc;
- (id)description;
- (id)initWithServiceName:(id)arg1 queue:(id)arg2 target:(id)arg3 remoteProtocol:(id)arg4;
- (void)invalidate;
- (void)resume;
- (id)serviceName;
- (void)setAutoReconnects:(BOOL)arg1;
- (void)setConnectionEstablishmentInvocation:(id)arg1;
- (void)setEstablishmentSelector:(SEL)arg1 andSendObject:(id)arg2;

@end
