/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

@class NSMutableURLRequest;

@interface YTAuthenticatorDeferredRequest : NSObject  {
    NSMutableURLRequest *_request;
    BOOL _accountAuthRequired;
}


- (void)setRequest:(id)arg1;
- (void)dealloc;
- (id)request;
- (BOOL)accountAuthRequired;
- (void)setAccountAuthRequired:(BOOL)arg1;

@end
