/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

@class YTCaptionTrack, <YTCaptionTrackRequestDelegate>;

@interface YTCaptionTrackRequest : YTXMLHTTPRequest  {
    <YTCaptionTrackRequestDelegate> *_delegate;
    YTCaptionTrack *_captionTrack;
}


- (id)captionTrack;
- (id)initCaptionTrackDataRequest:(id)arg1 withDelegate:(id)arg2;
- (void)_requestCaptionTrackDataWithURL:(id)arg1;
- (void)failWithError:(id)arg1;
- (void)dealloc;
- (int)parseData:(id)arg1;

@end
