/* Generated by RuntimeBrowser on iPhone OS 4.2.1
   Image: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */



@interface PTPTransport : NSObject 
{
    unsigned short _transportType;
    NSInteger _role;
    NSInteger _connectionStatus;
    id _delegate;
    BOOL _timedOut;
    BOOL _responseReceived;
}


- (unsigned short)transportType;
- (void)setTimedOut:(BOOL)arg1;
- (BOOL)timedOut;
- (NSInteger)role;
- (BOOL)sendResponse:(id)arg1;
- (BOOL)startResponder;
- (void)cancelTransaction:(id)arg1;
- (BOOL)connected;
- (void)abortPendingIO;
- (BOOL)startInitiator;
- (NSInteger)connectionStatus;
- (void)setResponseReceived:(BOOL)arg1;
- (BOOL)sendRequest:(id)arg1 needsData:(BOOL)arg2;
- (unsigned short)deviceStatus;
- (void)deviceReset;
- (id)init;
- (BOOL)sendEvent:(id)arg1;
- (void)setDelegate:(id)arg1;
- (BOOL)sendData:(id)arg1;
- (void)stop;

@end
