/* Generated by RuntimeBrowser.
 */

@protocol _INPBCreateTimerIntentResponse <NSObject>

@required

- (_INPBTimer *)createdTimer;
- (bool)hasCreatedTimer;
- (void)setCreatedTimer:(_INPBTimer *)arg1;

@end
