/* Generated by RuntimeBrowser.
 */

@protocol _UIViewModel

@required

- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })bounds;
- (struct CGPoint { double x1; double x2; })center;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frame;
- (NSArray *)mSubviews;
- (void)setMSubviews:(NSArray *)arg1;
- (id)stateData;
- (NSArray *)subviews;
- (<_UIViewModel> *)superview;
- (<_UIViewPresentation> *)viewPresentation;

@end
