/* Generated by RuntimeBrowser.
 */

@protocol PRSAuxiliaryInfo <NSObject>

@optional

- (NSString *)bottom_text;
- (NSString *)bottom_text_color;
- (NSString *)middle_text;
- (void)setBottom_text:(NSString *)arg1;
- (void)setBottom_text_color:(NSString *)arg1;
- (void)setMiddle_text:(NSString *)arg1;
- (void)setTop_text:(NSString *)arg1;
- (NSString *)top_text;

@end
