/* Generated by RuntimeBrowser.
 */

@protocol TSUIOChannel <NSObject>

@required

- (void)addBarrier:(void *)arg1; // needs 1 arg types, found 5: id, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id, void*
- (void)close;
- (void)setLowWater:(unsigned long long)arg1;

@end
