/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudDocs.framework/CloudDocs
 */

@interface BRSharingCopyShortTokenOperation : BROperation {
    NSURL * _fileURL;
    id  _shortTokenCompletionBlock;
}

@property (copy) id shortTokenCompletionBlock;

- (void).cxx_destruct;
- (void)finishWithResult:(id)arg1 error:(id)arg2;
- (id)initWithURL:(id)arg1;
- (void)main;
- (void)setShortTokenCompletionBlock:(id)arg1;
- (id)shortTokenCompletionBlock;

@end
