/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@class NSString, NSArray;

@interface TIWordSearchOperationGetCandidates : TIWordSearchOperation {
    SEL _action;
    NSString *_inputString;
    NSArray *_results;
    id _target;
    BOOL _withPrediction;
}

@property(readonly) NSString *inputString;
@property(retain) NSArray *results;
@property(readonly) SEL action;
@property(retain,readonly) id target;
@property(readonly) BOOL withPrediction;

- (SEL)action;
- (void)completeSearchOnMainThread;
- (void)dealloc;
- (id)initWithTIWordSearch:(id)arg1 inputString:(id)arg2 withPrediction:(BOOL)arg3 target:(id)arg4 action:(SEL)arg5;
- (id)inputString;
- (void)perform;
- (id)results;
- (void)setResults:(id)arg1;
- (id)target;
- (BOOL)withPrediction;

@end
