/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

@class WebTextIteratorPrivate;

@interface WebTextIterator : NSObject {
    WebTextIteratorPrivate *_private;
}

- (void)advance;
- (BOOL)atEnd;
- (id)currentNode;
- (id)currentRange;
- (id)currentText;
- (NSUInteger)currentTextLength;
- (const unsigned short*)currentTextPointer;
- (void)dealloc;
- (id)initWithRange:(id)arg1;

@end
