/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSString;

@interface AXEventTapPair : NSObject  {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id handler;

    NSString *identifier;
    int priority;
}

@property(copy) id handler;
@property(copy) NSString * identifier;
@property int priority;


- (id)identifier;
- (id)description;
- (void)dealloc;
- (void)setPriority:(int)arg1;
- (void)setHandler:(id)arg1;
- (id)handler;
- (int)priority;
- (void)setIdentifier:(id)arg1;

@end
