/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

@class NSNumber, NSString;

@interface ASMeetingResponseResponse : ASItem {
    NSString *_calendarId;
    NSString *_requestId;
    NSNumber *_status;
}

- (void)_addResult:(id)arg1;
- (id)asParseRules;
- (id)calendarId;
- (void)dealloc;
- (id)description;
- (id)requestId;
- (void)setCalendarId:(id)arg1;
- (void)setRequestId:(id)arg1;
- (void)setStatus:(id)arg1;
- (id)status;

@end
