/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDBulletinCategoryEntry : NSObject {
    NSString *_characteristicType;
    NSString *_serviceType;
}

@property (nonatomic, retain) NSString *characteristicType;
@property (nonatomic, retain) NSString *serviceType;

- (void).cxx_destruct;
- (id)characteristicType;
- (id)init;
- (id)initWithServiceType:(id)arg1 characteristicType:(id)arg2;
- (BOOL)isRelatedToCharacteristic:(id)arg1;
- (id)serviceType;
- (void)setCharacteristicType:(id)arg1;
- (void)setServiceType:(id)arg1;

@end
