/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSNumber, NSObject<OS_dispatch_queue>;

@interface HMMsgHandler : NSObject {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _messageHandler;

    NSObject<OS_dispatch_queue> *_receiverQueue;
    NSNumber *_token;
}

@property(copy) id messageHandler;
@property(retain) NSObject<OS_dispatch_queue> * receiverQueue;
@property(retain) NSNumber * token;

+ (id)msgHandler:(id)arg1 token:(id)arg2 receiverQueue:(id)arg3;

- (void).cxx_destruct;
- (id)initWithMessageHandler:(id)arg1 token:(id)arg2 receiverQueue:(id)arg3;
- (id)messageHandler;
- (id)receiverQueue;
- (void)setMessageHandler:(id)arg1;
- (void)setReceiverQueue:(id)arg1;
- (void)setToken:(id)arg1;
- (id)token;

@end
