/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@class MPAVItem, NSArray, NSDate, RadioGetTracksResponse, RadioStation;

@interface MPRadioStationPreparationContext : NSObject {
    RadioGetTracksResponse *_getTracksResponse;
    MPAVItem *_prefixItem;
    RadioStation *_station;
}

@property(readonly) MPAVItem * prefixItem;
@property(readonly) BOOL shouldIncrementSkipCount;
@property(readonly) NSDate * skipDate;
@property(readonly) RadioStation * station;
@property(readonly) NSArray * tracks;

- (void).cxx_destruct;
- (id)initWithGetTracksResponse:(id)arg1 station:(id)arg2 prefixItem:(id)arg3;
- (id)prefixItem;
- (BOOL)shouldIncrementSkipCount;
- (id)skipDate;
- (id)station;
- (id)tracks;

@end
