/* Generated by RuntimeBrowser
   Image: /System/Library/AccessibilityBundles/iAdFramework.axbundle/iAdFramework
 */

@interface ADBannerViewAccessibility_super : UIAccessibilitySafeCategory {
}

@end
