/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKEventDetailAttendeesAvatarListView : UIView <EKEventDetailAttendeesList> {
    NSArray * _accepted;
    NSMutableArray * _avatarViews;
    NSArray * _declined;
    bool  _groupsNames;
    bool  _highlighted;
    UIColor * _highlightedTextColor;
    NSArray * _maybe;
    NSArray * _noReply;
    UIColor * _textColor;
    NSArray * _ungrouped;
    UIViewController * _viewController;
}

@property (nonatomic, retain) NSArray *accepted;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, retain) NSArray *declined;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool groupsNames;
@property (readonly) unsigned long long hash;
@property (getter=isHighlighted, nonatomic) bool highlighted;
@property (nonatomic, retain) UIColor *highlightedTextColor;
@property (nonatomic, retain) NSArray *maybe;
@property (nonatomic, retain) NSArray *noReply;
@property (readonly) Class superclass;
@property (nonatomic, retain) UIColor *textColor;
@property (nonatomic, retain) NSArray *ungrouped;
@property (nonatomic) UIViewController *viewController;

- (void).cxx_destruct;
- (id)accepted;
- (id)declined;
- (bool)groupsNames;
- (id)highlightedTextColor;
- (bool)isHighlighted;
- (id)maybe;
- (id)noReply;
- (id)rowOfFaces:(id)arg1 withStatus:(id)arg2;
- (void)setAccepted:(id)arg1;
- (void)setDeclined:(id)arg1;
- (void)setGroupsNames:(bool)arg1;
- (void)setHighlighted:(bool)arg1;
- (void)setHighlightedTextColor:(id)arg1;
- (void)setMaybe:(id)arg1;
- (void)setNoReply:(id)arg1;
- (void)setTextColor:(id)arg1;
- (void)setUngrouped:(id)arg1;
- (void)setViewController:(id)arg1;
- (void)setup;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (id)textColor;
- (id)ungrouped;
- (id)viewController;

@end
