/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DAAPKit.framework/DAAPKit
 */

@class NSMutableData;

@interface _DKDAAPWriterContainer : NSObject {
    NSMutableData *_childData;
    unsigned int _code;
}

@property(retain) NSMutableData * childData;
@property(readonly) unsigned int code;

- (void).cxx_destruct;
- (id)childData;
- (unsigned int)code;
- (id)formattedOutputData;
- (id)initWithCode:(unsigned int)arg1;
- (void)setChildData:(id)arg1;

@end
