/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@class NSString, NSObject<OS_dispatch_queue>;

@interface MLSQLiteConnectionQueue : NSObject {
    NSString *_identifier;
    NSObject<OS_dispatch_queue> *_queue;
    BOOL _shouldUseDispatchGroupAPI;
}

@property(readonly) NSString * identifier;
@property(readonly) BOOL isOnQueue;
@property(retain) NSObject<OS_dispatch_queue> * queue;
@property(readonly) BOOL shouldUseDispatchGroupAPI;

+ (id)currentQueueConnectionIdentifier;
+ (id)mainThreadConnectionQueue;

- (void).cxx_destruct;
- (id)_initWithDispatchQueue:(id)arg1 identifier:(id)arg2 shouldUseDispatchGroupAPI:(BOOL)arg3;
- (void)dispatchAsync:(id)arg1;
- (void)dispatchAsyncOrInvokeImmediately:(id)arg1;
- (void)dispatchSync:(id)arg1;
- (void)dispatchSyncOrInvokeImmediately:(id)arg1;
- (id)identifier;
- (id)initWithDispatchQueue:(id)arg1 shouldUseDispatchGroupAPI:(BOOL)arg2;
- (BOOL)isOnQueue;
- (id)queue;
- (void)setQueue:(id)arg1;
- (BOOL)shouldUseDispatchGroupAPI;

@end
