/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@interface SSDownloadMonitorItem : NSObject <SSXPCCoding> {
    NSString * _clientIdentifier;
    int  _itemState;
    NSString * _representativeTitle;
    NSString * _statusString;
    int  _totalNumberOfItems;
    unsigned int  _transferTypes;
}

@property (nonatomic, copy) NSString *clientIdentifier;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (nonatomic) int itemState;
@property (nonatomic, copy) NSString *representativeTitle;
@property (nonatomic, copy) NSString *statusString;
@property (readonly) Class superclass;
@property (nonatomic) int totalNumberOfItems;
@property (nonatomic) unsigned int transferTypes;

- (id)clientIdentifier;
- (id)copyXPCEncoding;
- (void)dealloc;
- (id)initWithXPCEncoding:(id)arg1;
- (int)itemState;
- (id)representativeTitle;
- (void)setClientIdentifier:(id)arg1;
- (void)setItemState:(int)arg1;
- (void)setRepresentativeTitle:(id)arg1;
- (void)setStatusString:(id)arg1;
- (void)setTotalNumberOfItems:(int)arg1;
- (void)setTransferTypes:(unsigned int)arg1;
- (id)statusString;
- (int)totalNumberOfItems;
- (unsigned int)transferTypes;

@end
