/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

@class NSData, NSNumber, NSString;

@interface SSMachineDataRequest : SSRequest <SSXPCCoding> {
    NSNumber *_accountID;
    NSData *_actionData;
    NSString *_actionName;
    bool_allowsBootstrapCellularData;
    bool_waitsForPurchaseOperations;
}

@property(copy) NSNumber * accountIdentifier;
@property(copy) NSData * actionData;
@property(copy) NSString * actionName;
@property bool allowsBootstrapCellularData;
@property(copy,readonly) NSString * debugDescription;
@property(copy,readonly) NSString * description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property bool waitsForPurchaseOperations;

- (id)accountIdentifier;
- (id)actionData;
- (id)actionName;
- (bool)allowsBootstrapCellularData;
- (id)copyXPCEncoding;
- (void)dealloc;
- (id)initWithURLResponse:(id)arg1;
- (id)initWithXPCEncoding:(id)arg1;
- (void)setAccountIdentifier:(id)arg1;
- (void)setActionData:(id)arg1;
- (void)setActionName:(id)arg1;
- (void)setAllowsBootstrapCellularData:(bool)arg1;
- (void)setWaitsForPurchaseOperations:(bool)arg1;
- (void)startWithCompletionBlock:(id)arg1;
- (bool)waitsForPurchaseOperations;

@end
