/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AirTraffic.framework/AirTraffic
 */

@class NSMutableArray, NSMutableDictionary;

@interface ATAssetManager : NSObject  {
    NSMutableArray *_assets;
    NSMutableDictionary *_assetsByDataclass;
    NSMutableDictionary *_assetsByStoreID;
    NSMutableArray *_completedStoreAssets;
    unsigned int _completedAssets;
    unsigned int _totalAssetCount;
    NSMutableDictionary *_totalAssetCountByDataclass;
}


- (void)reset;
- (void)dealloc;
- (id)init;
- (BOOL)isEmpty;
- (BOOL)dataclassIsEmpty:(id)arg1;
- (void)removeCompletedStoreAsset:(id)arg1;
- (void)fixUpInstallOnlyAssetsForDataclass:(id)arg1;
- (id)assetManifestForDataclasses:(id)arg1;
- (void)dequeueAsset:(id)arg1;
- (id)uploadAssetsForDataclass:(id)arg1;
- (unsigned int)countOfSyncAssetsForDataclasses:(id)arg1;
- (id)assetsForDataclasses:(id)arg1;
- (id)bypassedRestoresForDataclass:(id)arg1;
- (id)restoreAssetsForDataclass:(id)arg1;
- (id)storeAssetsForDataclass:(id)arg1;
- (id)completedStoreAssets;
- (id)assetForDataclass:(id)arg1 identifier:(id)arg2;
- (id)assetForStoreID:(long long)arg1;
- (void)mapStoreIDToAsset:(id)arg1;
- (void)enqueueAsset:(id)arg1;
- (unsigned int)awaitingStoreCompletion;
- (id)assetProgressForAllDataclasses;
- (unsigned int)totalAssetCount;
- (void)_installSignalHandler;
- (void)enqueueAssets:(id)arg1;
- (unsigned int)currentAssetForDataclass:(id)arg1;
- (unsigned int)totalAssetCountForDataclass:(id)arg1;
- (id)assets;
- (unsigned int)currentAsset;

@end
