/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMMessageChatItem : IMChatItem {
}

- (id)description;
- (id)initWithMessage:(id)arg1;
- (id)message;

@end
