/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@class CKShareID, NSArray;

@interface CKModifyShareCommentsOperationInfo : CKOperationInfo {
    NSArray *_commentIDsToDelete;
    NSArray *_commentsToSave;
    CKShareID *_shareID;
}

@property(retain) NSArray * commentIDsToDelete;
@property(retain) NSArray * commentsToSave;
@property(retain) CKShareID * shareID;

+ (BOOL)supportsSecureCoding;

- (void).cxx_destruct;
- (id)commentIDsToDelete;
- (id)commentsToSave;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setCommentIDsToDelete:(id)arg1;
- (void)setCommentsToSave:(id)arg1;
- (void)setShareID:(id)arg1;
- (id)shareID;

@end
