/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudPhotoLibrary.framework/CloudPhotoLibrary
 */

@class <CPLEngineSyncTaskDelegate>, <NSCoding>, CPLEngineLibrary, NSString;

@interface CPLEngineSyncTask : NSObject {
    BOOL _cancelled;
    <CPLEngineSyncTaskDelegate> *_delegate;
    CPLEngineLibrary *_engineLibrary;
    BOOL _foreground;
    BOOL _paused;
    <NSCoding> *_transportUserIdentifier;
}

@property(getter=isCancelled) BOOL cancelled;
@property(retain) <CPLEngineSyncTaskDelegate> * delegate;
@property(readonly) CPLEngineLibrary * engineLibrary;
@property BOOL foreground;
@property(getter=isPaused) BOOL paused;
@property(readonly) NSString * taskIdentifier;
@property(retain) <NSCoding> * transportUserIdentifier;

+ (id)taskWithEngineLibrary:(id)arg1;

- (void).cxx_destruct;
- (void)_setCancelled:(BOOL)arg1;
- (void)_setPaused:(BOOL)arg1;
- (void)cancel;
- (id)delegate;
- (id)description;
- (unsigned int)diskPressureState;
- (id)engineLibrary;
- (BOOL)foreground;
- (id)initWithEngineLibrary:(id)arg1;
- (BOOL)isCancelled;
- (BOOL)isPaused;
- (void)launch;
- (void)pause;
- (void)resume;
- (void)setDelegate:(id)arg1;
- (void)setForeground:(BOOL)arg1;
- (void)setTransportUserIdentifier:(id)arg1;
- (void)taskDidFinishWithError:(id)arg1;
- (void)taskDidProgress:(float)arg1;
- (id)taskIdentifier;
- (id)transportUserIdentifier;

@end
