/* Generated by RuntimeBrowser on iPhone OS 3.0
   Image: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */



@interface PLDiskController : NSObject 
{
    double _lastFSCheck;
    long long _freeDiskSpaceThreshold;
    struct { 
        unsigned int dontWarnOfDiskSpace : 1; 
        unsigned int probablyLowOnDiskSpace : 1; 
        unsigned int didSetFreeDiskSpaceThreshold : 1; 
        unsigned int extra : 29; 
    } _flags;
}

+ (id)sharedInstance;

- (id)init;
- (void)noteFileSystemChanged:(id)arg1;
- (long long)diskSpaceAvailableForUse;
- (long long)freeDiskSpaceThreshold;
- (BOOL)hasEnoughDiskToTakePicture;
- (void)presentDiskSpaceWarningIfNecessary:(BOOL)arg1;
- (void)alertSheet:(id)arg1 buttonClicked:(NSInteger)arg2;

@end
