/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCMutableShallowCopyPair : FCShallowCopyPair

- (void)setFirst:(id)arg1;
- (void)setSecond:(id)arg1;

@end
