/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKGameStatServiceInterface : GKServiceInterface

+ (void)configureInterface:(id)arg1;
+ (id)interfaceProtocol;

@end
