/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSArray, NSString, NSData, NSDictionary;

@interface FTProvisionMessage : FTMessage <NSCopying> {
    NSString *_service;
    NSString *_realm;
    NSData *_csr;
    NSDictionary *_authenticationInfo;
    NSString *_userID;
    NSArray *_URIs;
    NSData *_responseCertificate;
    NSArray *_responseBindings;
    NSString *_protocolVersion;
}

@property(copy) NSString * service;
@property(copy) NSString * realm;
@property(copy) NSData * csr;
@property(copy) NSString * protocolVersion;
@property(copy) NSString * userID;
@property(copy) NSDictionary * authenticationInfo;
@property(copy) NSArray * URIs;
@property(copy) NSData * responseCertificate;
@property(copy) NSArray * responseBindings;


- (void)setService:(id)arg1;
- (id)messageBody;
- (int)command;
- (void)setProtocolVersion:(id)arg1;
- (id)protocolVersion;
- (id)URIs;
- (id)responseCertificate;
- (void)setURIs:(id)arg1;
- (void)setAuthenticationInfo:(id)arg1;
- (void)setUserID:(id)arg1;
- (void)setCsr:(id)arg1;
- (void)setRealm:(id)arg1;
- (id)responseBindings;
- (id)userID;
- (id)realm;
- (id)service;
- (void)setResponseCertificate:(id)arg1;
- (id)authenticationInfo;
- (id)csr;
- (void)setResponseBindings:(id)arg1;
- (void)handleResponseDictionary:(id)arg1;
- (id)additionalMessageHeaders;
- (int)responseCommand;
- (BOOL)wantsBagKey;
- (BOOL)wantsHTTPHeaders;
- (BOOL)wantsCompressedBody;
- (id)requiredKeys;
- (BOOL)wantsBinaryPush;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;
- (void)dealloc;
- (id)bagKey;

@end
