/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface _INPBMessage : PBCodable <NSCopying> {
    struct { 
        int *list; 
        unsigned int count; 
        unsigned int size; 
    }  _attributes;
    NSString * _content;
    _INPBDateTime * _dateSent;
    NSString * _groupName;
    NSString * _identifier;
    NSMutableArray * _recipients;
    _INPBContact * _sender;
    PBUnknownFields * _unknownFields;
}

@property (nonatomic, readonly) int*attributes;
@property (nonatomic, readonly) unsigned int attributesCount;
@property (nonatomic, retain) NSString *content;
@property (nonatomic, retain) _INPBDateTime *dateSent;
@property (nonatomic, retain) NSString *groupName;
@property (nonatomic, readonly) BOOL hasContent;
@property (nonatomic, readonly) BOOL hasDateSent;
@property (nonatomic, readonly) BOOL hasGroupName;
@property (nonatomic, readonly) BOOL hasIdentifier;
@property (nonatomic, readonly) BOOL hasSender;
@property (nonatomic, retain) NSString *identifier;
@property (nonatomic, retain) NSMutableArray *recipients;
@property (nonatomic, retain) _INPBContact *sender;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;

// Image: /System/Library/Frameworks/Intents.framework/Intents

+ (id)options;
+ (Class)recipientType;

- (void).cxx_destruct;
- (int)StringAsAttributes:(id)arg1;
- (void)addAttribute:(int)arg1;
- (void)addRecipient:(id)arg1;
- (int)attributeAtIndex:(unsigned int)arg1;
- (int*)attributes;
- (id)attributesAsString:(int)arg1;
- (unsigned int)attributesCount;
- (void)clearAttributes;
- (void)clearRecipients;
- (id)content;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)dateSent;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (id)groupName;
- (BOOL)hasContent;
- (BOOL)hasDateSent;
- (BOOL)hasGroupName;
- (BOOL)hasIdentifier;
- (BOOL)hasSender;
- (unsigned int)hash;
- (id)identifier;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)recipientAtIndex:(unsigned int)arg1;
- (id)recipients;
- (unsigned int)recipientsCount;
- (id)sender;
- (void)setAttributes:(int*)arg1 count:(unsigned int)arg2;
- (void)setContent:(id)arg1;
- (void)setDateSent:(id)arg1;
- (void)setGroupName:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setRecipients:(id)arg1;
- (void)setSender:(id)arg1;
- (id)unknownFields;
- (void)writeTo:(id)arg1;

// Image: /System/Library/PrivateFrameworks/SiriClientFlow.framework/SiriClientFlow

+ (id)fromJSONProtoDictionary:(id)arg1;

- (id)toJSONProtoDictionary;

@end
