/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@class NSString;

@interface ISDialogTextField : NSObject {
    NSInteger _keyboardType;
    BOOL _secure;
    NSString *_title;
    NSString *_value;
}

@property(retain) NSString *value; /* unknown property attribute: V_value */
@property(retain) NSString *title; /* unknown property attribute: V_title */
@property(getter=isSecure) BOOL secure; /* unknown property attribute: V_secure */
@property NSInteger keyboardType; /* unknown property attribute: V_keyboardType */

+ (id)textFieldWithTitle:(id)arg1;

- (void)dealloc;
- (BOOL)isSecure;
- (NSInteger)keyboardType;
- (void)setKeyboardType:(NSInteger)arg1;
- (void)setSecure:(BOOL)arg1;
- (void)setTitle:(id)arg1;
- (void)setValue:(id)arg1;
- (id)title;
- (id)value;

@end
