/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@interface ISUserNotification : NSObject {
    int _allowedRetryCount;
    int _currentRetryCount;
    NSDictionary *_dictionary;
    unsigned long _optionFlags;
    NSDictionary *_userInfo;
}

@property int allowedRetryCount;
@property int currentRetryCount;
@property (readonly) NSDictionary *dictionary;
@property (readonly) unsigned long optionFlags;
@property (retain) NSDictionary *userInfo;

- (int)allowedRetryCount;
- (struct __CFUserNotification { }*)copyUserNotification;
- (int)currentRetryCount;
- (void)dealloc;
- (id)dictionary;
- (id)init;
- (id)initWithDictionary:(id)arg1 options:(unsigned long)arg2;
- (unsigned long)optionFlags;
- (void)setAllowedRetryCount:(int)arg1;
- (void)setCurrentRetryCount:(int)arg1;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;

@end
