/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUITableViewController : SearchUIKeyboardableTableViewController {
    BOOL  _hasCheckedInsetSectionsOverride;
    BOOL  _insetSectionsOverride;
    unsigned int  _style;
}

@property BOOL hasCheckedInsetSectionsOverride;
@property BOOL insetSectionsOverride;
@property unsigned int style;

- (BOOL)hasCheckedInsetSectionsOverride;
- (id)initWithUIStyle:(unsigned int)arg1;
- (BOOL)insetSectionsOverride;
- (void)setAllowsHeaderViewsToFloat:(BOOL)arg1;
- (void)setHasCheckedInsetSectionsOverride:(BOOL)arg1;
- (void)setInsetSectionsOverride:(BOOL)arg1;
- (void)setStyle:(unsigned int)arg1;
- (unsigned int)style;

@end
