/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

@class NSString, NSDictionary;

@interface ALCity : NSObject  {
    int _identifier;
    NSString *_localeCode;
    NSString *_timeZone;
    float _longitude;
    float _latitude;
    NSString *_yahooCode;
    NSString *_name;
    NSString *_unlocalizedName;
    NSString *_countryName;
    NSString *_unlocalizedCountryName;
    NSString *_countryOverride;
    NSString *_unlocalizedCountryOverride;
    NSString *_identifierForCPCity;
    BOOL _localizationAttempted;
}

@property(readonly) NSString * classicIdentifier;
@property(readonly) NSDictionary * properties;
@property(retain) NSString * name;
@property(retain) NSString * unlocalizedName;
@property(retain) NSString * countryName;
@property(retain) NSString * unlocalizedCountryName;
@property(retain) NSString * countryOverride;
@property(retain) NSString * unlocalizedCountryOverride;
@property(retain) NSString * yahooCode;
@property float latitude;
@property float longitude;
@property(retain) NSString * timeZone;
@property(retain) NSString * localeCode;
@property int identifier;


- (void)setTimeZone:(id)arg1;
- (id)initWithProperties:(id)arg1;
- (int)identifier;
- (id)timeZone;
- (unsigned int)hash;
- (void)setName:(id)arg1;
- (void)setIdentifier:(int)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)name;
- (id)init;
- (void)dealloc;
- (id)description;
- (float)latitude;
- (float)longitude;
- (id)properties;
- (id)countryName;
- (void)setCountryName:(id)arg1;
- (void)setLatitude:(float)arg1;
- (void)setLongitude:(float)arg1;
- (void)ensureLocalized;
- (id)displayNameIncludingCountry:(BOOL)arg1;
- (id)classicIdentifier;
- (void)setUnlocalizedName:(id)arg1;
- (void)setUnlocalizedCountryName:(id)arg1;
- (id)unlocalizedCountryOverride;
- (void)setUnlocalizedCountryOverride:(id)arg1;
- (void)setYahooCode:(id)arg1;
- (void)setLocaleCode:(id)arg1;
- (id)countryOverride;
- (id)unlocalizedCountryName;
- (id)unlocalizedName;
- (id)yahooCode;
- (id)localeCode;
- (void)setCountryOverride:(id)arg1;
- (id)initWithSQLRow:(char **)arg1;

@end
