/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/FactoryDiags.framework/FactoryDiags
 */

@interface OSDAccelerometerData : NSObject  {
    float x;
    float y;
    float z;
    double timestamp;
}

@property float x;
@property float y;
@property float z;
@property double timestamp;


- (double)timestamp;
- (void)setTimestamp:(double)arg1;
- (id)init;
- (void)setZ:(float)arg1;
- (float)z;
- (void)setY:(float)arg1;
- (float)y;
- (void)setX:(float)arg1;
- (float)x;

@end
