/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class NSString, DOMHTMLFormElement, DOMValidityState, DOMNodeList;

@interface DOMHTMLKeygenElement : DOMHTMLElement  {
}

@property BOOL autofocus;
@property(copy) NSString * challenge;
@property BOOL disabled;
@property(readonly) DOMHTMLFormElement * form;
@property(copy) NSString * keytype;
@property(copy) NSString * name;
@property(readonly) NSString * type;
@property(readonly) BOOL willValidate;
@property(readonly) DOMValidityState * validity;
@property(readonly) NSString * validationMessage;
@property(readonly) DOMNodeList * labels;


- (void)setName:(id)arg1;
- (id)name;
- (id)type;
- (id)form;
- (void)setDisabled:(BOOL)arg1;
- (BOOL)disabled;
- (void)setKeytype:(id)arg1;
- (id)keytype;
- (void)setChallenge:(id)arg1;
- (id)challenge;
- (void)setCustomValidity:(id)arg1;
- (BOOL)checkValidity;
- (id)labels;
- (id)validationMessage;
- (id)validity;
- (BOOL)willValidate;
- (void)setAutofocus:(BOOL)arg1;
- (BOOL)autofocus;

@end
