/* Generated by RuntimeBrowser
   Image: /System/Library/AccessibilityBundles/PreferencesFramework.axbundle/PreferencesFramework
 */

@interface PSEditableTableCellAccessibility : PSEditableTableCellAccessibility_super {
}

+ (void)_initializeSafeCategory;

- (BOOL)isAccessibilityElement;

@end
