/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@class UIImageView, MKSearchResult, MKPanorama, MKPanoramaLoader;

@interface MKStreetViewThumbnail : UIView <MKPanoramaThumbnailDelegate> {
    BOOL _needsUpdate;
    MKPanorama *_panorama;
    MKPanoramaLoader *_panoramaLoader;
    UIImageView *_pegman;
    BOOL _requestedOnce;
    MKSearchResult *_searchResult;
    UIImageView *_thumbnail;
}

@property(retain) MKPanorama * panorama;
@property(readonly) MKPanoramaLoader * panoramaLoader;
@property(retain) MKSearchResult * searchResult;

- (void)_setNeedsUpdate;
- (void)_updateImage;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)loader:(id)arg1 didFailWithError:(id)arg2;
- (void)loader:(id)arg1 didServiceRequest:(id)arg2;
- (void)loader:(id)arg1 didServiceRequests:(id)arg2;
- (void)loader:(id)arg1 willProcessRequests:(id)arg2 needSort:(BOOL)arg3;
- (void)panorama:(id)arg1 didLoadThumbnailForCoordinate:(struct { double x1; double x2; })arg2;
- (id)panorama;
- (id)panoramaLoader;
- (id)searchResult;
- (void)setPanorama:(id)arg1;
- (void)setSearchResult:(id)arg1;

@end
