/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NotesShared.framework/NotesShared
 */

@interface ICAttachmentImageLoadingOperation : NSOperation {
    short  _attachmentType;
    NSCache * _cache;
    NSMutableArray * _completionHandlers;
    NSManagedObjectID * _mediaObjectID;
    NSURL * _mediaURL;
}

@property (nonatomic) short attachmentType;
@property (nonatomic, retain) NSCache *cache;
@property (nonatomic, retain) NSMutableArray *completionHandlers;
@property (nonatomic, retain) NSManagedObjectID *mediaObjectID;
@property (nonatomic, retain) NSURL *mediaURL;

- (void).cxx_destruct;
- (id)addCompletionHandler:(id)arg1;
- (short)attachmentType;
- (id)cache;
- (id)completionHandlers;
- (id)initWithCache:(id)arg1 media:(id)arg2 attachmentType:(short)arg3 completionHandler:(id)arg4;
- (void)main;
- (id)mediaObjectID;
- (id)mediaURL;
- (void)removeCompletionHandler:(id)arg1 cancelIfNoneLeft:(bool)arg2;
- (void)setAttachmentType:(short)arg1;
- (void)setCache:(id)arg1;
- (void)setCompletionHandlers:(id)arg1;
- (void)setMediaObjectID:(id)arg1;
- (void)setMediaURL:(id)arg1;

@end
