/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class EDCell, EDWorkbook, ECMappingContext;

@interface EDFormulaHelper : NSObject {
     /* Encoded args for previous method: @20@0:4@8@12B16 */
     /* Encoded args for previous method: @20@0:4@8@12B16 */
    EDCell *mCell;
    ECMappingContext *mMappingContext;
    EDWorkbook *mWorkbook;
    /* Warning: Unrecognized filer type: 'B' using 'void*' */ void*mImporting;
}

+ (id)formulaHelperWithWorkbook:(id)arg1 withCell:(id)arg2 isImport:(/* Warning: Unrecognized filer type: 'B' using 'void*' */ void*)arg3;

- (NSUInteger)addExternalAddInName:(id)arg1;
- (void)dealloc;
- (id)initWithWorkbook:(id)arg1 withCell:(id)arg2 isImport:(/* Warning: Unrecognized filer type: 'B' using 'void*' */ void*)arg3;
- (BOOL)isCurrentSheet:(id)arg1;
- (NSUInteger)resolveAddInLinkReference;
- (NSUInteger)resolveFile:(id)arg1;
- (NSUInteger)resolveFirstSheet:(id)arg1 lastSheet:(id)arg2;
- (NSUInteger)resolveName:(id)arg1;
- (NSUInteger)resolveSheet:(id)arg1;
- (id)resolveTable:(id)arg1;
- (NSUInteger)resolveTableColumn:(id)arg1 columnName:(id)arg2;
- (NSUInteger)resolveTableToSheetId:(id)arg1;

@end
