/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSArray;

@interface OABTableSortedIntArray : NSObject {
    NSArray *mIntArray;
}

- (void)dealloc;
- (NSUInteger)dim;
- (NSUInteger)indexOfInt:(NSUInteger)arg1;
- (id)initWithIntSet:(id)arg1;
- (NSUInteger)intAtIndex:(NSUInteger)arg1;

@end
