/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OADPresetTextWarp : OADTextWarp  {
    int mPresetTextWarpType;
}


- (int)presetTextWarpType;
- (void)setPresetTextWarpType:(int)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;

@end
