/* Generated by RuntimeBrowser on iPhone OS 3.0
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */



@interface OADRelativeRect : NSObject <NSCopying>
{
    float mLeft;
    float mTop;
    float mRight;
    float mBottom;
}


- (id)init;
- (id)initWithLeft:(float)arg1 top:(float)arg2 right:(float)arg3 bottom:(float)arg4;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (float)left;
- (void)setLeft:(float)arg1;
- (float)top;
- (void)setTop:(float)arg1;
- (float)right;
- (void)setRight:(float)arg1;
- (float)bottom;
- (void)setBottom:(float)arg1;

@end
