/* Generated by RuntimeBrowser on iPhone OS 3.0
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */



@interface OADThemeOverrides : OADBaseStylesBase 
{
}


- (void)setColorScheme:(id)arg1;
- (void)setStyleMatrix:(id)arg1;
- (void)setFontScheme:(id)arg1;

@end
