/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class OADDrawable;

@interface PDBuild : NSObject  {
    BOOL mIsAnimateBackground;
    OADDrawable *mDrawable;
}


- (BOOL)isAnimateBackground;
- (void)setIsAnimateBackground:(BOOL)arg1;
- (void)setDrawable:(id)arg1;
- (id)drawable;
- (id)init;
- (void)dealloc;

@end
