/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
 */

@class NSDictionary, NSString, UIColor;

@interface MPUExtrasGridSectionHeaderStyle : NSObject {
    struct UIEdgeInsets { 
        float top; 
        float left; 
        float bottom; 
        float right; 
    NSDictionary *_defaultFontAttributes;
    } _insets;
    float _textBaselineDescender;
    float _textBaselineHeight;
    UIColor *_textColor;
    NSString *_textStyle;
}

@property(retain) NSDictionary * defaultFontAttributes;
@property struct UIEdgeInsets { float x1; float x2; float x3; float x4; } insets;
@property float textBaselineDescender;
@property float textBaselineHeight;
@property(retain) UIColor * textColor;
@property(retain) NSString * textStyle;

- (void).cxx_destruct;
- (id)defaultFontAttributes;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })insets;
- (void)setDefaultFontAttributes:(id)arg1;
- (void)setInsets:(struct UIEdgeInsets { float x1; float x2; float x3; float x4; })arg1;
- (void)setTextBaselineDescender:(float)arg1;
- (void)setTextBaselineHeight:(float)arg1;
- (void)setTextColor:(id)arg1;
- (void)setTextStyle:(id)arg1;
- (float)textBaselineDescender;
- (float)textBaselineHeight;
- (id)textColor;
- (id)textStyle;

@end
