/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXReusableObjectPool : NSObject {
    NSMutableDictionary * __objectCreationBlocksByReuseIdentifier;
    NSMutableDictionary * __reusableObjectsByReuseIdentifier;
    <PXReusableObjectPoolDelegate> * _delegate;
    struct { 
        BOOL respondsToDidCreateReusableObject; 
        BOOL respondsToObjectBecameReusable; 
        BOOL respondsToObjectPreparedForReuse; 
    }  _delegateFlags;
}

@property (nonatomic, readonly) NSMutableDictionary *_objectCreationBlocksByReuseIdentifier;
@property (nonatomic, readonly) NSMutableDictionary *_reusableObjectsByReuseIdentifier;
@property (nonatomic) <PXReusableObjectPoolDelegate> *delegate;

- (void).cxx_destruct;
- (id)_objectCreationBlocksByReuseIdentifier;
- (id)_reusableObjectsByReuseIdentifier;
- (void)checkInReusableObject:(id)arg1;
- (id)checkOutReusableObjectWithReuseIdentifier:(int)arg1;
- (id)delegate;
- (id)init;
- (void)registerReusableObjectForReuseIdentifier:(int)arg1 creationHandler:(id /* block */)arg2;
- (void)setDelegate:(id)arg1;

@end
