/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Stocks.framework/Stocks
 */

@class NSArray, UIColor, <GraphRenderOperationDelegate>, StockGraphImageSet;

@interface GraphRenderOperation : NSObject {
    struct CGSize { 
        float width; 
        float height; 
    struct CGSize { 
        float width; 
        float height; 
    BOOL _cancelled;
    UIColor *axisColor;
    UIColor *backgroundLinesColor;
    <GraphRenderOperationDelegate> *delegate;
    BOOL detailedMode;
    NSArray *dottedLinePositions;
    StockGraphImageSet *graphImageSet;
    BOOL letterPress;
    UIColor *lineColor;
    } lineGraphSize;
    NSArray *linePointCounts;
    float lineWidth;
    unsigned long long maxVolume;
    struct CGPoint { float x1; float x2; } *points;
    BOOL roundLineCaps;
    UIColor *shadowLineColor;
    float volumeBarWidth;
    struct { float x1; unsigned long long x2; } *volumeBars;
    unsigned int volumeCount;
    } volumeGraphSize;
}

@property(retain) UIColor * axisColor;
@property(retain) UIColor * backgroundLinesColor;
@property(getter=isCancelled,readonly) BOOL cancelled;
@property <GraphRenderOperationDelegate> * delegate;
@property BOOL detailedMode;
@property(retain) NSArray * dottedLinePositions;
@property(retain) StockGraphImageSet * graphImageSet;
@property BOOL letterPress;
@property(retain) UIColor * lineColor;
@property struct CGSize { float x1; float x2; } lineGraphSize;
@property(retain) NSArray * linePointCounts;
@property float lineWidth;
@property unsigned long long maxVolume;
@property struct CGPoint { float x1; float x2; }* points;
@property BOOL roundLineCaps;
@property(retain) UIColor * shadowLineColor;
@property float volumeBarWidth;
@property struct { float x1; unsigned long long x2; }* volumeBars;
@property unsigned int volumeCount;
@property struct CGSize { float x1; float x2; } volumeGraphSize;

+ (struct CGGradient { }*)LineBackgroundGradient;

- (void).cxx_destruct;
- (void)_deliverDelegateCallback;
- (id)axisColor;
- (id)backgroundLinesColor;
- (void)cancel;
- (id)delegate;
- (BOOL)detailedMode;
- (id)dottedLinePositions;
- (id)graphImageSet;
- (id)init;
- (BOOL)isCancelled;
- (BOOL)letterPress;
- (id)lineColor;
- (struct CGSize { float x1; float x2; })lineGraphSize;
- (id)linePointCounts;
- (float)lineWidth;
- (unsigned long long)maxVolume;
- (struct CGPoint { float x1; float x2; }*)points;
- (void)render;
- (void)renderGraphLineInContext:(struct CGContext { }*)arg1 withColor:(id)arg2 offset:(struct CGPoint { float x1; float x2; })arg3;
- (void)renderLineGraph;
- (void)renderVolumeGraph;
- (BOOL)roundLineCaps;
- (void)setAxisColor:(id)arg1;
- (void)setBackgroundLinesColor:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDetailedMode:(BOOL)arg1;
- (void)setDottedLinePositions:(id)arg1;
- (void)setGraphImageSet:(id)arg1;
- (void)setLetterPress:(BOOL)arg1;
- (void)setLineColor:(id)arg1;
- (void)setLineGraphSize:(struct CGSize { float x1; float x2; })arg1;
- (void)setLinePointCounts:(id)arg1;
- (void)setLineWidth:(float)arg1;
- (void)setMaxVolume:(unsigned long long)arg1;
- (void)setPoints:(struct CGPoint { float x1; float x2; }*)arg1;
- (void)setRoundLineCaps:(BOOL)arg1;
- (void)setShadowLineColor:(id)arg1;
- (void)setVolumeBarWidth:(float)arg1;
- (void)setVolumeBars:(struct { float x1; unsigned long long x2; }*)arg1;
- (void)setVolumeCount:(unsigned int)arg1;
- (void)setVolumeGraphSize:(struct CGSize { float x1; float x2; })arg1;
- (id)shadowLineColor;
- (float)volumeBarWidth;
- (struct { float x1; unsigned long long x2; }*)volumeBars;
- (unsigned int)volumeCount;
- (struct CGSize { float x1; float x2; })volumeGraphSize;

@end
