/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PowerlogLiteOperators.framework/PowerlogLiteOperators
 */

@interface PLBackgroundTransferEvent : NSObject {
    NSString * _bundleID;
    NSDate * _startDate;
    NSMutableSet * _taskUUIDs;
}

@property (retain) NSString *bundleID;
@property (retain) NSDate *startDate;
@property (retain) NSMutableSet *taskUUIDs;

- (void).cxx_destruct;
- (id)bundleID;
- (id)description;
- (void)setBundleID:(id)arg1;
- (void)setStartDate:(id)arg1;
- (void)setTaskUUIDs:(id)arg1;
- (id)startDate;
- (id)taskUUIDs;

@end
