/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
 */

@interface PUAngleValueFilter : PUValueFilter {
}

- (double)updatedValue:(double)arg1 withTargetValue:(double)arg2;

@end
