/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
 */

@interface PUPhotoBrowserControllerPhoneCameraSpec : PUPhotoBrowserControllerPhoneSpec {
}

- (BOOL)isInCamera;
- (unsigned int)supportedInterfaceOrientations;

@end
