/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthKitUI.framework/HealthKitUI
 */

@interface _HKTimePeriodChartPoint : NSObject <HKChartPoint> {
    id _userInfo;
    NSDate *_xValue;
    NSNumber *_yValue;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (readonly) Class superclass;
@property (nonatomic, retain) id userInfo;
@property (nonatomic, retain) NSDate *xValue;
@property (nonatomic, retain) NSNumber *yValue;

- (void).cxx_destruct;
- (id)allYValues;
- (id)description;
- (id)maxYValue;
- (id)minYValue;
- (void)setUserInfo:(id)arg1;
- (void)setXValue:(id)arg1;
- (void)setYValue:(id)arg1;
- (id)userInfo;
- (id)xValue;
- (id)yValue;
- (id)yValueForKey:(id)arg1;

@end
