/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthKitUI.framework/HealthKitUI
 */

@class <HKMedicalIDEditorCellEditDelegate>, HKCaretOptionalTextField, NSString, UILabel, UIView;

@interface HKMedicalIDEditorCell : UITableViewCell <UITextFieldDelegate> {
    <HKMedicalIDEditorCellEditDelegate> *_editDelegate;
    UIView *_horizontalSeparatorView;
    HKCaretOptionalTextField *_inputTextField;
    UILabel *_labelLabel;
    float _minimumLabelWidth;
    UIView *_verticalSeparatorView;
}

@property(copy,readonly) NSString * debugDescription;
@property(copy,readonly) NSString * description;
@property <HKMedicalIDEditorCellEditDelegate> * editDelegate;
@property(readonly) unsigned int hash;
@property(readonly) HKCaretOptionalTextField * inputTextField;
@property(retain) NSString * label;
@property(readonly) UILabel * labelLabel;
@property float minimumLabelWidth;
@property(readonly) Class superclass;

+ (BOOL)showsLabelAndValue;

- (void).cxx_destruct;
- (void)beginEditing;
- (void)commitEditing;
- (void)dealloc;
- (id)editDelegate;
- (id)formattedValue;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)inputTextField;
- (id)label;
- (id)labelLabel;
- (void)layoutSubviews;
- (float)minimumLabelWidth;
- (void)setEditDelegate:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setMinimumLabelWidth:(float)arg1;
- (id)shortenedFormattedValue;
- (BOOL)textFieldShouldBeginEditing:(id)arg1;
- (void)updateValueLabel;
- (void)valueDidChange;

@end
