/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
 */

@interface FBUIApplicationWorkspace : FBWorkspace

- (id)_applicationServer;
- (Class)_sceneClassForIdentity:(id)arg1;
- (Class)_serverClass;

@end
