/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/GameController.framework/GameController
 */

@interface GCControllerElement : NSObject

@property (getter=isAnalog, readonly) BOOL analog;
@property (readonly) GCControllerElement *collection;

- (BOOL)_setValue:(float)arg1;
- (id)collection;
- (BOOL)isAnalog;
- (BOOL)setHIDValue:(struct __IOHIDValue { }*)arg1;
- (float)value;

@end
