/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/GameController.framework/GameController
 */

@interface GCControllerSFDelegate : NSObject <NSUserActivityDelegate> {
    NSUserActivity * _activity;
    id  _completionHandler;
}

@property (nonatomic, copy) id completionHandler;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)completionHandler;
- (void)fireCompletionHandler;
- (void)setCompletionHandler:(id)arg1;
- (void)startScan;
- (void)userActivityWasContinued:(id)arg1;

@end
