/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
 */

@interface IDSCKDatabaseOperation : NSObject

+ (Class)__class;
+ (id)alloc;

@end
