/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

@class NSSet;

@interface CalDAVNotificationContainerSyncTaskGroup : CoreDAVContainerSyncTaskGroup  {
    NSSet *_notificationTypeNamesToFetch;
}

@property(retain) NSSet * notificationTypeNamesToFetch;


- (void)dealloc;
- (BOOL)shouldFetchResourceWithEtag:(id)arg1 propertiesToValues:(id)arg2;
- (id)copyGetTaskWithURL:(id)arg1;
- (id)copyAdditionalResourcePropertiesToFetch;
- (void)setNotificationTypeNamesToFetch:(id)arg1;
- (id)initWithFolderURL:(id)arg1 previousCTag:(id)arg2 previousSyncToken:(id)arg3 accountInfoProvider:(id)arg4 taskManager:(id)arg5;
- (id)notificationTypeNamesToFetch;

@end
