/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Librarian.framework/Librarian
 */

@interface LBItem : NSObject {
    NSMutableDictionary *_attributes;
    NSString *_path;
    id _replacement;
    NSURL *_url;
}

@property (nonatomic) id replacement;

- (id)_attributes;
- (id)attributeForName:(id)arg1;
- (id)attributeNames;
- (id)attributesForNames:(id)arg1;
- (void)dealloc;
- (id)initWithURL:(id)arg1;
- (id)initWithURL:(id)arg1 itemUpdateInfo:(id)arg2;
- (id)path;
- (id)replacement;
- (void)setReplacement:(id)arg1;
- (void)updateInfo:(id)arg1;
- (id)url;
- (id)valueForKey:(id)arg1;

@end
