/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CryptoTokenKit.framework/CryptoTokenKit
 */

@interface TKTokenWatcher : NSObject <TKProtocolTokenWatcher> {
    NSXPCConnection * _connection;
    id  _insertionHandler;
    NSMutableDictionary * _removalHandlers;
    NSObject<OS_dispatch_semaphore> * _semaphore;
    NSMutableArray * _tokenIDs;
}

@property (readonly) NSArray *tokenIDs;

- (void).cxx_destruct;
- (void)addRemovalHandler:(id)arg1 forTokenID:(id)arg2;
- (void)dealloc;
- (id)init;
- (id)initWithInsertionHandler:(id)arg1;
- (void)insertedToken:(id)arg1 reply:(id)arg2;
- (void)removedToken:(id)arg1 reply:(id)arg2;
- (void)setup;
- (id)tokenIDs;

@end
