/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
 */

@interface WBSHistorySession : NSObject {
    NSDate * _startDate;
}

@property (nonatomic, readonly) BOOL isCurrentSession;
@property (nonatomic, readonly) NSDate *startDate;

+ (id)currentSession;

- (void).cxx_destruct;
- (unsigned int)hash;
- (id)initWithSessionStartDate:(id)arg1;
- (BOOL)isCurrentSession;
- (BOOL)isEqual:(id)arg1;
- (id)startDate;

@end
