/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface _PUEmptyAssetsDataSource : PUAssetsDataSource

- (id)indexPathForAssetCollection:(id)arg1;
- (id)indexPathForAssetReference:(id)arg1;
- (long long)numberOfSubItemsAtIndexPath:(id)arg1;

@end
