/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUAdjustmentsToolControllerSpec : PUPhotoEditToolControllerSpec {
}

@property(readonly) long long visualSliderThumbnailCount;
@property(readonly) double visualSliderThumbnailLongSide;
@property(readonly) double visualSliderThumbnailShortSide;

- (id)newModeBarView;
- (long long)visualSliderThumbnailCount;
- (double)visualSliderThumbnailLongSide;
- (double)visualSliderThumbnailShortSide;

@end
