/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@class <PUAlbumListTableViewCellDelegate>;

@interface PUAlbumListTableViewCell : UITableViewCell {
    <PUAlbumListTableViewCellDelegate> *_stateChangeDelegate;
}

@property <PUAlbumListTableViewCellDelegate> * stateChangeDelegate;

- (void).cxx_destruct;
- (void)setStateChangeDelegate:(id)arg1;
- (id)stateChangeDelegate;
- (void)willTransitionToState:(unsigned int)arg1;

@end
