/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CommunicationsSetupUI.framework/CommunicationsSetupUI
 */

@class CNFRegSigninLearnMoreView;

@interface CNFRegSplashSignInController : CNFRegSignInController {
    CNFRegSigninLearnMoreView *_signInView;
}

- (id)_existingLearnMoreViewForSection:(long long)arg1;
- (id)_existingLearnMoreViewForSpecifier:(id)arg1;
- (void)_setFieldsEnabled:(bool)arg1 animated:(bool)arg2;
- (bool)passwordIsEmpty;
- (id)passwordTextField;
- (void)setPasswordText:(id)arg1;
- (void)setUsernameText:(id)arg1;
- (id)specifierList;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (bool)usernameIsEmpty;
- (id)usernameTextField;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;

@end
