/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CommunicationsSetupUI.framework/CommunicationsSetupUI
 */

@interface CNFRegAliasDetailController : CNFRegListController {
    CNFRegAlias * _alias;
    PSSpecifier * _removeButtonSpecifier;
    PSSpecifier * _removeGroupSpecifier;
    NSArray * _resendValidationSpecifierGroup;
}

@property (nonatomic, retain) CNFRegAlias *alias;

- (void).cxx_destruct;
- (void)_buildSpecifierCache:(id)arg1;
- (void)_setupEventHandlers;
- (BOOL)_shouldShowResendButton;
- (void)_showAliasValidationError:(id)arg1;
- (void)_showResendGroup:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_updateUIAnimated:(BOOL)arg1;
- (id)alias;
- (id)bundle;
- (void)forgetAliasTapped:(id)arg1;
- (id)initWithRegController:(id)arg1 alias:(id)arg2;
- (void)resendValidationEmailTapped:(id)arg1;
- (void)setAlias:(id)arg1;
- (void)setRemoveAliasEnabled:(BOOL)arg1 animated:(BOOL)arg2;
- (void)showRemoveAliasConfirmation;
- (id)specifierList;
- (void)systemApplicationDidEnterBackground;
- (void)systemApplicationWillEnterForeground;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;

@end
