/* Generated by RuntimeBrowser
   Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit
 */

@interface UIScrubberTimeViewAccessibility : UIScrubberTimeViewAccessibility_super {
}

+ (void)_initializeSafeCategory;

- (id)accessibilityLabel;

@end
