/* Generated by RuntimeBrowser on iPhone OS 4.1
   Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit
 */



@interface UIToolbarAccessibility : UIToolbarAccessibility_super 
{
}

+ (void)_initializeSafeCategory;

- (id)_accessibilityHitTest:(struct CGPoint { float x1; float x2; })arg1 withEvent:(id)arg2;
- (unsigned long long)accessibilityTraits;
- (void)_buttonBarFinishedAnimating;
- (void)_buttonUp:(id)arg1;
- (void)_showButtons:(NSInteger*)arg1 withCount:(NSInteger)arg2 group:(NSInteger)arg3 withDuration:(double)arg4 adjustPositions:(BOOL)arg5 skipTag:(NSInteger)arg6;

@end
