/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Message.framework/Message
 */

@class NSArray, MFError, ActivityMonitor, Account;

@interface AccountValidator : NSObject {
    struct { 
        unsigned int useSSL : 1; 
        unsigned int incomingServerSupportsSSL : 1; 
        unsigned int smtpServerSupportsSSL : 1; 
        unsigned int validationInProgress : 1; 
        unsigned int canceled : 1; 
        unsigned int unused : 27; 
    Account *_account;
    ActivityMonitor *_accountValidationActivity;
    id _delegate;
    } _flags;
    NSArray *_incomingServerAuthSchemes;
    MFError *_incomingServerValidationError;
    NSArray *_smtpServerAuthSchemes;
    MFError *_smtpServerValidationError;
}

- (void)_backgroundValidateAccountFinished:(id)arg1 authSchemes:(id)arg2;
- (BOOL)_incomingServerValid;
- (id)_ispAccountInfo;
- (BOOL)_outgoingServerValid;
- (void)_updateValidationStatusForAccount:(id)arg1 status:(id)arg2;
- (void)_validateAccount:(id)arg1;
- (void)_validateAccountInBackground:(id)arg1;
- (id)account;
- (BOOL)accountIsValid;
- (BOOL)accountSupportsSSL;
- (BOOL)accountValidationCanceled;
- (void)cancelValidation;
- (void)dealloc;
- (id)error;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)stop;
- (void)validateAccount:(id)arg1 useSSL:(BOOL)arg2;

@end
