/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iAdCore.framework/iAdCore
 */

@class NSString;

@interface ADSRVClientRecord : NSObject {
    int _bannerCount;
    NSString *_bundleId;
    double _connectTime;
    double _disconnectTime;
}

@property int bannerCount;
@property(copy) NSString * bundleId;
@property double connectTime;
@property double disconnectTime;

- (int)bannerCount;
- (id)bundleId;
- (double)connectTime;
- (void)dealloc;
- (double)disconnectTime;
- (void)setBannerCount:(int)arg1;
- (void)setBundleId:(id)arg1;
- (void)setConnectTime:(double)arg1;
- (void)setDisconnectTime:(double)arg1;

@end
