/* Generated by RuntimeBrowser on iPhone OS 4.0
   Image: /System/Library/AccessibilityBundles/MapKitFramework.axbundle/MapKitFramework
 */



@interface MKAnnotationContainerViewAccessibility_super : UIAccessibilitySafeCategory 
{
}

+ (void)_initializeSafeCategory;

- (void)accessibilityZoomOutAtPoint:(struct CGPoint { float x1; float x2; })arg1;
- (void)accessibilityZoomInAtPoint:(struct CGPoint { float x1; float x2; })arg1;
- (void)addAnnotation:(id)arg1;
- (void)addSubview:(id)arg1;
- (void)dealloc;
- (NSInteger)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(NSInteger)arg1;
- (NSInteger)accessibilityElementCount;
- (BOOL)isAccessibilityElement;
- (unsigned long long)accessibilityTraits;
- (void)removeAnnotation:(id)arg1;
- (id)_addViewForAnnotation:(id)arg1;
- (void)_calloutAccessoryControlTapped:(id)arg1;

@end
