/* Generated by RuntimeBrowser on iPhone OS 4.1
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */



@interface _NSScalarObjectID : _NSCoreManagedObjectID 
{
}


- (id)_retainedURIString;
- (id)initWithPK64:(long long)arg1;
- (long long)_referenceData64;
- (void)dealloc;

@end
