/* Generated by RuntimeBrowser on iPhone OS 4.1
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@class NSEntityDescription, NSMutableDictionary, NSString, NSData, NSManagedObjectModel;



@interface NSEntityDescription : NSObject <NSCoding, NSCopying, NSFastEnumeration>
{
    NSInteger _cd_rc;
    id _reserved1;
    NSString *_versionHashModifier;
    NSData *_versionHash;
    NSManagedObjectModel *_model;
    NSString *_classNameForEntity;
    Class _instanceClass;
    NSString *_name;
    NSEntityDescription *_rootentity;
    NSEntityDescription *_superentity;
    NSMutableDictionary *_subentities;
    NSMutableDictionary *_properties;
    id _propertyMapping;
    struct _NSRange { NSUInteger x1; NSUInteger x2; } *_propertyRanges;
    struct __entityDescriptionFlags { 
        unsigned int _isAbstract : 1; 
        unsigned int _shouldValidateOnSave : 1; 
        unsigned int _isImmutable : 1; 
        unsigned int _isFlattened : 1; 
        unsigned int _skipValidation : 1; 
        unsigned int _hasPropertiesIndexedBySpotlight : 1; 
        unsigned int _hasPropertiesStoredInTruthFile : 1; 
        unsigned int _rangesAreInDataBlob : 1; 
        unsigned int _hasAttributesWithExternalDataReferences : 1; 
        unsigned int _reservedEntityDescription : 23; 
    } _entityDescriptionFlags;
    void *_extraIvars;
    NSMutableDictionary *_userInfo;
    id _flattenedSubentities;
    id **_kvcPropertyAccessors;
    long _modelsReferenceIDForEntity;
}

+ (id)entityForName:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)insertNewObjectForEntityForName:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)_MOClassName;
+ (void)initialize;

- (id)attributeKeys;
- (BOOL)_isEditable;
- (id)managedObjectClassName;
- (id)_newDictionaryContainingPropertiesOfType:(NSUInteger)arg1;
- (id)_newMappingForPropertiesOfRange:(NSUInteger)arg1;
- (id)attributesByName;
- (id)relationshipsByName;
- (BOOL)isAbstract;
- (BOOL)isKindOfEntity:(id)arg1;
- (id)superentity;
- (id)subentities;
- (void)setSubentities:(id)arg1;
- (id)subentitiesByName;
- (id)toManyRelationshipKeys;
- (id)toOneRelationshipKeys;
- (id)relationshipsWithDestinationEntity:(id)arg1;
- (id)inverseForRelationshipKey:(id)arg1;
- (void)setManagedObjectClassName:(id)arg1;
- (void)setAbstract:(BOOL)arg1;
- (id)versionHashModifier;
- (void)setVersionHashModifier:(id)arg1;
- (void)setRenamingIdentifier:(id)arg1;
- (void)setElementID:(id)arg1;
- (id)elementID;
- (void)_addSubentity:(id)arg1;
- (void)_addProperty:(id)arg1;
- (id)knownKeysMappingStrategy;
- (void)_setManagedObjectModel:(id)arg1;
- (id)_propertiesOfType:(NSUInteger)arg1;
- (id)_relationshipNamesByType:(BOOL)arg1;
- (Class)_entityClass;
- (id)_attributeNamed:(id)arg1;
- (id)_localRelationshipNamed:(id)arg1;
- (id)_relationshipNamed:(id)arg1;
- (void)_setIsEditable:(BOOL)arg1;
- (id)_subentityNamed:(id)arg1;
- (void)_setSuperentity:(id)arg1;
- (void)_removeSubentity:(id)arg1;
- (struct __CFSet { }*)_collectSubentities;
- (struct _NSRange { NSUInteger x1; NSUInteger x2; }*)_propertyRangesByType;
- (BOOL)_isInheritedPropertyNamed:(id)arg1;
- (unsigned long)_offsetRelationshipIndex:(unsigned long)arg1 fromSuperEntity:(id)arg2 andIsToMany:(BOOL)arg3;
- (id)_allPropertyNames;
- (void*)_leopardStyleRelationshipsByName;
- (void*)_leopardStyleAttributesByName;
- (void)_removePropertyNamed:(id)arg1;
- (void)_removeProperty:(id)arg1;
- (id)_new_implicitlyObservedKeys;
- (void)_setModelsReferenceID:(long)arg1;
- (id)_sortedSubentities;
- (BOOL)_isFlattened;
- (void)_setIsFlattened:(BOOL)arg1;
- (void)_flattenProperties;
- (void)_stripForMigration;
- (BOOL)_skipValidation;
- (void)_restoreValidation;
- (BOOL)_hasAttributesWithExternalDataReferences;
- (BOOL)_hasPropertiesIndexedBySpotlight;
- (BOOL)_hasPropertiesStoredInTruthFile;
- (void)_writeIntoData:(id)arg1 propertiesDict:(id)arg2 uniquedPropertyNames:(id)arg3 uniquedStrings:(id)arg4 uniquedData:(id)arg5 uniquedMappings:(id)arg6 entities:(id)arg7;
- (id)_propertySearchMapping;
- (long)_modelsReferenceID;
- (void)_throwIfNotEditable;
- (id)_initWithName:(id)arg1;
- (void)_createCachesAndOptimizeState;
- (id)_propertyNamed:(id)arg1;
- (BOOL)_subentitiesIncludes:(id)arg1;
- (id)managedObjectModel;
- (id)_rootEntity;
- (id)renamingIdentifier;
- (id)propertiesByName;
- (id)versionHash;
- (void)setUserInfo:(id)arg1;
- (void)finalize;
- (void)setName:(id)arg1;
- (id)name;
- (id)userInfo;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (BOOL)isEqual:(id)arg1;
- (NSUInteger)hash;
- (NSUInteger)retainCount;
- (id)description;
- (id)init;
- (void)release;
- (id)retain;
- (NSUInteger)countByEnumeratingWithState:(struct { unsigned long x1; id *x2; unsigned long *x3; unsigned long x4[5]; }*)arg1 objects:(id*)arg2 count:(NSUInteger)arg3;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)properties;
- (void)setProperties:(id)arg1;

@end
