/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/OpenGLES.framework/OpenGLES
 */

@interface EAGLSharegroup : NSObject {
    struct _EAGLSharegroupPrivate { struct IMG_OGLEGL_Interface_TAG {} *x1; struct EGLSysContext_TAG { 
            NSUInteger mbx_service; 
            NSUInteger shared_connection; 
            NSUInteger shared_id; 
            struct _opaque_pthread_mutex_t { 
                long __sig; 
                BOOL __opaque[40]; 
            } display_lock; 
        } x2; void *x3; } *_private;
}

- (void)dealloc;
- (id)init;

@end
