/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKJSUIAnimatorDOMFeature : IKJSObject <SKJSUIAnimatorDOMFeature> {
    SKUIAnimatorDOMFeature * _feature;
}

- (void).cxx_destruct;
- (void)animate:(id)arg1 :(id)arg2;
- (id)initWithAppContext:(id)arg1 DOMFeature:(id)arg2;

@end
