/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUISearchFacet : NSObject <NSCopying> {
    NSArray *_labels;
    NSString *_queryParameter;
    NSArray *_values;
}

@property (nonatomic, copy) NSArray *labels;
@property (nonatomic, copy) NSString *queryParameter;
@property (nonatomic, copy) NSArray *values;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)initWithFacetDictionary:(id)arg1;
- (id)labels;
- (id)queryParameter;
- (void)setLabels:(id)arg1;
- (void)setQueryParameter:(id)arg1;
- (void)setValues:(id)arg1;
- (id)values;

@end
