/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUILinkButton : UIButton {
    int _arrowStyle;
}

@property (nonatomic, readonly) int arrowStyle;

+ (id)buttonWithArrowStyle:(int)arg1;

- (float)_linkImagePaddingLeft;
- (void)_reloadIcons;
- (int)arrowStyle;
- (id)initWithArrowStyle:(int)arg1;
- (void)layoutSubviews;
- (void)setTitleColor:(id)arg1 forState:(unsigned int)arg2;
- (struct CGSize { float x1; float x2; })sizeThatFits:(struct CGSize { float x1; float x2; })arg1;
- (void)sizeToFit;
- (void)tintColorDidChange;

@end
