/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIMenuBarTemplateDocumentViewControllerEmbeddedPaletteHost : UIView {
    UIView * _titleView;
}

@property (nonatomic, retain) UIView *titleView;

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setTitleView:(id)arg1;
- (id)titleView;

@end
