/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/AccountSettings.framework/AccountSettings
 */

@interface DeviceLocalAccount : BasicAccount <AccountCreationProtocol, AccountSettingsUIAccount> {
}

+ (id)accountWithBasicAccount:(id)arg1;
+ (id)basicAccountProperties;
+ (id)localizedReferenceToSyncSourceStringForDataClass:(id)arg1;
+ (BOOL)isTetheredSyncingDataclass:(id)arg1;
+ (id)tetheredSourceForDataClass:(id)arg1;
+ (id)_identifier;
+ (id)typeString;
+ (id)localizedSyncSourceStringForDataClass:(id)arg1 forBeginningOfSentence:(BOOL)arg2;
+ (id)displayedAccountTypeString;
+ (id)displayedShortAccountTypeString;
+ (void*)createSyncDataSourceForDataclass:(id)arg1 options:(id)arg2;

- (id)syncStoreIdentifier;
- (id)displayName;
- (id)identifier;
- (void)_saveChangesToOnMyDeviceAccount;
- (BOOL)_setTetheredDataSourceEnabled:(BOOL)arg1 forDataclass:(id)arg2;
- (BOOL)_deleteDataSourceForDataclass:(id)arg1;
- (void)setEnabled:(BOOL)arg1 forDataclass:(id)arg2;
- (id)uniqueId;
- (void)setTetheredEnabled:(BOOL)arg1 forDataclass:(id)arg2;
- (void)deleteLocalDataSourceForDataclass:(id)arg1;
- (void)hideLocalStoreForDataclass:(id)arg1;
- (void)showLocalStoreIfAppropriateForDataclass:(id)arg1;
- (BOOL)otherAccountEnabledForDataclass:(id)arg1;
- (BOOL)supportsPush;

@end
