/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

@interface GMMMetadata : PBCodable {
    BOOL _hasNeedsLinkStreetRange;
    BOOL _needsLinkStreetRange;
}

@property(readonly) BOOL hasNeedsLinkStreetRange; /* unknown property attribute: V_hasNeedsLinkStreetRange */
@property BOOL needsLinkStreetRange; /* unknown property attribute: V_needsLinkStreetRange */

+ (id)standardMetadata;

- (void)dealloc;
- (id)description;
- (BOOL)hasNeedsLinkStreetRange;
- (id)init;
- (BOOL)needsLinkStreetRange;
- (BOOL)readFrom:(id)arg1;
- (void)setNeedsLinkStreetRange:(BOOL)arg1;
- (void)writeTo:(id)arg1;

@end
