/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Contacts
 */

@interface CNAbstractActivityAlertDescription : CNPropertyDescription <CNAbstractPropertyDescription>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void*)ABValueFromCNValue:(id)arg1;
- (id)CNValueFromABValue:(void*)arg1;
- (bool)isValue:(id)arg1 equivalentToValue:(id)arg2;
- (Class)valueClass;

@end
