/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@class UIButton, UILabel;

@interface DDLinksEventController : UIViewController {
    UIButton *_button;
    UILabel *_label;
    struct __DDResult { } *_result;
}

- (void)buttonClicked:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)eventEditViewController:(id)arg1 didCompleteWithAction:(int)arg2;
- (id)initWithResult:(struct __DDResult { }*)arg1;
- (id)nibBundle;
- (id)nibName;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLoad;
- (void)viewDidUnload;

@end
