/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PassKit.framework/PassKit
 */

@interface PKAddPassButton : UIButton {
    int  _addPassButtonStyle;
    struct CGSize { 
        double width; 
        double height; 
    }  _boundsSize;
    CAFilter * _highlightFilter;
    BOOL  _highlighted;
    struct CGSize { 
        double width; 
        double height; 
    }  _iconSize;
    UIImageView * _iconView;
    CAShapeLayer * _layer;
    PKShapeView * _maskView;
    UILabel * _multiLineLabel;
    struct CGSize { 
        double width; 
        double height; 
    }  _multilineSize;
    UILabel * _singleLineLabel;
    struct CGSize { 
        double width; 
        double height; 
    }  _singlelineSize;
}

@property (nonatomic) int addPassButtonStyle;

+ (id)addPassButtonWithStyle:(int)arg1;
+ (Class)layerClass;

- (void).cxx_destruct;
- (void)_adjustVisibleLabel;
- (void)_applyStyle;
- (void)_createHighlightFilterIfNecessary;
- (void)_sharedInit;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (int)addPassButtonStyle;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithAddPassButtonStyle:(int)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (void)layoutSubviews;
- (void)setAddPassButtonStyle:(int)arg1;
- (void)setHighlighted:(BOOL)arg1;

@end
