/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CompassUI.framework/CompassUI
 */

@interface CUICalibration : NSObject

+ (void)_insertRemoteViewController:(id)arg1;
+ (void)_removeRemoteViewController;
+ (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
+ (void)dismissCalibrationAlert;
+ (void)load;
+ (Class)remoteViewControllerClass;
+ (id)serviceViewControllerClassName;
+ (void)showCalibrationAlert;

@end
