/* Generated by RuntimeBrowser on iPhone OS 4.1
   Image: /System/Library/AccessibilityBundles/GameKitFramework.axbundle/GameKitFramework
 */



@interface GKLeaderboardCellContentsAccessibility_super : UIAccessibilitySafeCategory 
{
}

+ (void)_initializeSafeCategory;

- (id)accessibilityLabel;
- (BOOL)isAccessibilityElement;

@end
