/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileBackup.framework/MobileBackup
 */

@class NSObject<MBConnectionHandler>, NSObject<OS_dispatch_queue>, NSObject<OS_xpc_object>;

@interface MBConnection : NSObject {
    NSObject<OS_xpc_object> *_conn;
    NSObject<OS_dispatch_queue> *_eventQueue;
    NSObject<MBConnectionHandler> *_handler;
}

@property NSObject<MBConnectionHandler> * messageHandler;

- (void)_handleXPCError:(id)arg1;
- (void)_handleXPCEvent:(id)arg1;
- (void)_setEventHandlerForXPCConnection;
- (void)cancel;
- (void)dealloc;
- (id)eventQueue;
- (id)initWithServiceName:(id)arg1 eventQueue:(id)arg2;
- (id)initWithXPCConnection:(id)arg1 eventQueue:(id)arg2;
- (id)messageHandler;
- (void)resume;
- (void)sendMessage:(id)arg1;
- (id)sendMessageWithReplyAndSync:(id)arg1 error:(id*)arg2;
- (void)setMessageHandler:(id)arg1;
- (void)suspend;

@end
