/* Generated by RuntimeBrowser on iPhone OS 4.1
   Image: /System/Library/Frameworks/AssetsLibrary.framework/AssetsLibrary
 */

@class MLAlbum, ALAssetsLibrary, ALAssetsFilter;



@interface ALAssetsGroupPrivate : NSObject <ALAssetsLibraryAsset>
{
    MLAlbum *_album;
    BOOL _loadedAssets;
    ALAssetsFilter *_assetsFilter;
    NSUInteger _groupType;
    BOOL _isValid;
    ALAssetsLibrary *_library;
}

@property ALAssetsLibrary *library;
@property BOOL isValid;
@property NSUInteger groupType;
@property(retain) ALAssetsFilter *assetsFilter;
@property(retain) MLAlbum *album;


- (void)resetAssets;
- (id)assetsFilter;
- (void)libraryWillDisappear;
- (void)libraryDidChange;
- (void)setIsValid:(BOOL)arg1;
- (id)initWithAlbum:(id)arg1 library:(id)arg2;
- (void)setGroupType:(NSUInteger)arg1;
- (NSUInteger)groupType;
- (void)populateAssets;
- (void)setAssetsFilter:(id)arg1;
- (void)setAlbum:(id)arg1;
- (BOOL)isValid;
- (void)dealloc;
- (id)library;
- (void)setLibrary:(id)arg1;
- (id)album;

@end
