/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SAAppsLaunchApp : SABaseClientBoundCommand

@property (nonatomic, copy) NSString *launchId;

+ (id)launchApp;
+ (id)launchAppWithDictionary:(id)arg1 context:(id)arg2;

- (id)encodedClassName;
- (id)groupIdentifier;
- (id)launchId;
- (BOOL)requiresResponse;
- (void)setLaunchId:(id)arg1;

@end
