/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SAUITemplateImageView : SAUITemplateBaseItem <SAUITemplateMonogrammable>

@property (nonatomic) float alpha;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) SAUIImageResource *image;
@property (nonatomic, copy) NSArray *monogramName;
@property (nonatomic, copy) NSString *style;
@property (readonly) Class superclass;

+ (id)imageView;
+ (id)imageViewWithDictionary:(id)arg1 context:(id)arg2;

- (float)alpha;
- (id)encodedClassName;
- (id)groupIdentifier;
- (id)image;
- (id)monogramName;
- (void)setAlpha:(float)arg1;
- (void)setImage:(id)arg1;
- (void)setMonogramName:(id)arg1;
- (void)setStyle:(id)arg1;
- (id)style;

@end
