/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/GameKit.framework/GameKit
 */

@interface GKButton : UIButton {
}

- (id)_backgroundForState:(NSUInteger)arg1 usesBackgroundForNormalState:(BOOL*)arg2;
- (NSInteger)buttonType;
- (id)initWithTheme:(id)arg1;
- (struct CGSize { float x1; float x2; })sizeThatFits:(struct CGSize { float x1; float x2; })arg1;

@end
