/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/GameKit.framework/Frameworks/GameCenterUI.framework/GameCenterUI
 */

@interface GKHostedTurnBasedViewController : GKHostedViewController {
}

- (id)_presentingViewController;
- (void)didGetRemoteViewController;
- (id)hostSideViewControllerClassName;
- (void)presentRemoteViewControllerIfNeeded;
- (id)remoteTurnBasedViewController;
- (id)serviceSideViewControllerClassName;
- (id)turnBasedViewController;

@end
