/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIView;

@interface _UITableViewCellSeparatorView : UIView {
    UIView *_backgroundView;
    BOOL _drawsWithVibrantLightMode;
    UIView *_overlayView;
}

@property BOOL drawsWithVibrantLightMode;

- (void)dealloc;
- (BOOL)drawsWithVibrantLightMode;
- (void)layoutSubviews;
- (void)setDrawsWithVibrantLightMode:(BOOL)arg1;

@end
