/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSDocumentDifferenceSize;

@interface NSDocumentDifferenceSizeTriple : NSObject {
    NSDocumentDifferenceSize *_betweenPreservingPreviousVersionAndSaving;
    NSDocumentDifferenceSize *_betweenPreviousSavingAndSaving;
    NSDocumentDifferenceSize *_dueToRecentChangesBeforeSaving;
}

@property(readonly) NSDocumentDifferenceSize * betweenPreservingPreviousVersionAndSaving;
@property(readonly) NSDocumentDifferenceSize * betweenPreviousSavingAndSaving;
@property(readonly) NSDocumentDifferenceSize * dueToRecentChangesBeforeSaving;

- (id)betweenPreservingPreviousVersionAndSaving;
- (id)betweenPreviousSavingAndSaving;
- (void)dealloc;
- (id)description;
- (id)dueToRecentChangesBeforeSaving;
- (id)init;

@end
