/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIActivityItemImageRep : NSObject {
    id  _asset;
    id  _dataProvider;
    id  _thumbnailProvider;
}

@property (nonatomic, retain) id asset;
@property (nonatomic, copy) id dataProvider;
@property (nonatomic, copy) id thumbnailProvider;

+ (id)activityItemImageRepWithAsset:(id)arg1 thumbnailProvider:(id)arg2 dataProvider:(id)arg3;

- (void).cxx_destruct;
- (id)asset;
- (id)data;
- (id)dataProvider;
- (void)setAsset:(id)arg1;
- (void)setDataProvider:(id)arg1;
- (void)setThumbnailProvider:(id)arg1;
- (id)thumbnail;
- (id)thumbnailProvider;

@end
