/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@class CALayer, NSArray, NSMutableDictionary, NSString, UIImage, UIKBRenderConfig, UIView, _UIInputViewContent;

@interface UIInputView : UIView <UISplittableInputView> {
    struct CGSize { 
        double width; 
        double height; 
    struct CGSize { 
        double width; 
        double height; 
    struct CGSize { 
        double width; 
        double height; 
    double _contentRatio;
    } _defaultSize;
    double _gapWidth;
    } _leftContentSize;
    _UIInputViewContent *_leftContentView;
    double _leftOffset;
    UIImage *_mergedImage;
    NSMutableDictionary *_mergedSliceMap;
    UIKBRenderConfig *_renderConfig;
    } _rightContentSize;
    _UIInputViewContent *_rightContentView;
    UIImage *_splitImage;
    NSMutableDictionary *_splitSliceMap;
    long long _style;
    double _transitionGap;
    CALayer *_transitionLayer;
    double _transitionLeftOffset;
    double _transitionRatio;
    NSArray *_visibleLayers;
    bool_disableSplitSupport;
    bool_isTransitioning;
    bool_suppressBackgroundStyling;
}

@property(retain) UIImage * _mergedImage;
@property(retain) NSMutableDictionary * _mergedSliceMap;
@property(retain) UIImage * _splitImage;
@property(retain) NSMutableDictionary * _splitSliceMap;
@property double contentRatio;
@property(copy,readonly) NSString * debugDescription;
@property(copy,readonly) NSString * description;
@property(readonly) unsigned long long hash;
@property(readonly) long long inputViewStyle;
@property(readonly) UIView * leftContentView;
@property struct CGSize { double x1; double x2; } leftContentViewSize;
@property(readonly) UIView * rightContentView;
@property struct CGSize { double x1; double x2; } rightContentViewSize;
@property(readonly) Class superclass;

+ (void)_setupAppearanceIfNecessary;

- (double)_additionalClipHeight;
- (void)_beginSplitTransitionIfNeeded:(double)arg1 gapWidth:(double)arg2;
- (int)_clipCornersOfView:(id)arg1;
- (struct CGSize { double x1; double x2; })_defaultSize;
- (bool)_disableSplitSupport;
- (void)_endSplitTransitionIfNeeded:(bool)arg1;
- (id)_inheritedRenderConfig;
- (bool)_isSplit;
- (bool)_isToolbars;
- (bool)_isTransitioning;
- (id)_mergedImage;
- (id)_mergedSliceMap;
- (void)_setDisableSplitSupport:(bool)arg1;
- (void)_setLeftOffset:(double)arg1 gapWidth:(double)arg2;
- (void)_setNeedsContentSizeUpdate;
- (void)_setProgress:(double)arg1 boundedBy:(double)arg2;
- (void)_setRenderConfig:(id)arg1;
- (void)_setSuppressBackgroundStyling:(bool)arg1;
- (id)_splitBorderedBackgroundWithCorners:(unsigned long long)arg1;
- (id)_splitImage;
- (id)_splitSliceMap;
- (bool)_supportsSplit;
- (bool)_suppressBackgroundStyling;
- (id)_toolbarBorderedBackground;
- (void)_updateBackgroundColor;
- (void)_updateClipCorners;
- (void)_updateWithSize:(struct CGSize { double x1; double x2; })arg1;
- (double)contentRatio;
- (void)dealloc;
- (void)didEndSplitTransition;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inputViewStyle:(long long)arg2;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (long long)inputViewStyle;
- (void)layoutMergedSubviews;
- (void)layoutSplitSubviewsWithLeftContentSize:(struct CGSize { double x1; double x2; })arg1 rightContentSize:(struct CGSize { double x1; double x2; })arg2;
- (id)leftContentView;
- (struct CGSize { double x1; double x2; })leftContentViewSize;
- (bool)pointInside:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (id)rightContentView;
- (struct CGSize { double x1; double x2; })rightContentViewSize;
- (void)setBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setContentRatio:(double)arg1;
- (void)setFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setInputViewStyle:(long long)arg1;
- (void)setLeftContentViewSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setRightContentViewSize:(struct CGSize { double x1; double x2; })arg1;
- (void)set_mergedImage:(id)arg1;
- (void)set_mergedSliceMap:(id)arg1;
- (void)set_splitImage:(id)arg1;
- (void)set_splitSliceMap:(id)arg1;
- (id)tintColor;
- (void)updateMergedSubviewConstraints;
- (void)updateSplitSubviewContraintsWithLeftContentSize:(struct CGSize { double x1; double x2; })arg1 rightContentSize:(struct CGSize { double x1; double x2; })arg2;
- (void)willBeginSplitTransition;

@end
