/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIMutableUserNotificationCategory : UIUserNotificationCategory {
    NSString *identifier;
}

@property (nonatomic, copy) NSString *identifier;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)identifier;
- (void)setActions:(id)arg1 forContext:(unsigned int)arg2;
- (void)setIdentifier:(id)arg1;

@end
