/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UISegmentLabel : UILabel {
    UILabel *_associatedLabel;
}

@property (nonatomic) UILabel *associatedLabel;

- (id)_associatedScalingLabel;
- (id)_disabledFontColor;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (id)associatedLabel;
- (id)init;
- (void)setAssociatedLabel:(id)arg1;

@end
