/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class ABRingtoneTableController, UITableView;

@interface ABRingtonePicker : UIView  {
    UITableView *_table;
    ABRingtoneTableController *_tableController;
    id _delegate;
    BOOL _isTextTone;
}

@property id delegate;


- (void)displayScrollerIndicators;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)setAVController:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 avController:(id)arg2 asRingtonePicker:(BOOL)arg3;
- (void)stopPlaying;
- (void)setShowsNone:(BOOL)arg1;
- (void)setSelectedRingtoneIdentifier:(id)arg1;
- (void)ringtoneManagerContentsChanged:(id)arg1;
- (void)ringtoneTableController:(id)arg1 willPlayRingtoneWithIdentifier:(id)arg2;
- (id)selectedRingtoneIdentifier;
- (void)setShowsRingtonesStore:(BOOL)arg1;
- (void)setNoneString:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 avController:(id)arg2;
- (void)_reloadData;
- (void)setShowsDefault:(BOOL)arg1;
- (void)setShowsNothingSelected:(BOOL)arg1;
- (void)buildUIWithAVController:(id)arg1;
- (void)stopPlayingWithFadeOut:(BOOL)arg1;
- (void)finishedWithPicker;
- (void)ringtoneTableController:(id)arg1 selectedRingtoneWithIdentifier:(id)arg2;
- (float)contentHeight;

@end
