/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOLogMsgStateMapRestore : PBCodable <NSCopying> {
    NSMutableArray * _targetLayouts;
}

@property (nonatomic, retain) NSMutableArray *targetLayouts;

+ (Class)targetLayoutType;

- (void)addTargetLayout:(id)arg1;
- (void)clearTargetLayouts;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)setTargetLayouts:(id)arg1;
- (id)targetLayoutAtIndex:(unsigned int)arg1;
- (id)targetLayouts;
- (unsigned int)targetLayoutsCount;
- (void)writeTo:(id)arg1;

@end
