/* Generated by RuntimeBrowser.
   Image: /System/Library/Frameworks/QuickLook.framework/QuickLook
 */

@class NSMutableDictionary;

@interface QLDisplayBundleLoader : NSObject  {
    NSMutableDictionary *_displayBundlesById;
}

+ (id)sharedLoader;

- (void)dealloc;
- (id)init;
- (id)copyDisplayBundleWithPreviewItem:(id)arg1 displayBundleIdentifier:(id)arg2;
- (Class)loadDisplayBundle:(id)arg1;
- (void)_lookForDisplayBundles;
- (Class)displayBundleClassForDocumentType:(id)arg1;

@end
