/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

@class NSMutableDictionary;

@interface CoreDAVProp : CoreDAVItem <CoreDAVParsingAcceptingTopLevelItems> {
    NSMutableDictionary *_propValues;
}

@property(readonly) NSDictionary *propValues;

+ (BOOL)acceptsTopLevelLeaves;
+ (BOOL)ignoresUnknownChildren;
+ (BOOL)parsingWithSubItems;

- (void)addNewTopLevelItem:(id)arg1;
- (id)copyCoreDAVParseRules;
- (void)dealloc;
- (id)description;
- (id)propValues;

@end
