/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RelevanceEngine.framework/RelevanceEngine
 */

@interface REDisabledDataSourceLoader : REDataSourceLoader

- (void)_loadBundleConfigurationsUsingBlock:(id /* block */)arg1;
- (void)_loadClassesUsingBlock:(id /* block */)arg1;
- (bool)isEqual:(id)arg1;

@end
