/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RelevanceEngine.framework/RelevanceEngine
 */

@interface REWorkoutRelevanceProviderManager : RERelevanceProviderManager <REPredictorObserver> {
    NSDate * _lastWorkoutDate;
    unsigned long long  _state;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)_features;
+ (Class)_relevanceProviderClass;

- (void).cxx_destruct;
- (void)_prepareForUpdate;
- (id)_valueForProvider:(id)arg1 feature:(id)arg2;
- (void)collectLoggableState:(id /* block */)arg1;
- (id)initWithQueue:(id)arg1;
- (void)pause;
- (void)predictorDidUpdate:(id)arg1;
- (void)resume;

@end
