/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetWriterInputInternal : NSObject {
    NSObject<OS_dispatch_queue> *appendFailureReadWriteQueue;
    BOOL attachedToMetadataAdaptor;
    BOOL attachedToPixelBufferAdaptor;
    AVAssetWriterInputHelper *helper;
    NSObject<OS_dispatch_queue> *helperQueue;
    int numberOfAppendFailures;
    AVAssetWriterInputPassDescriptionResponder *passDescriptionResponder;
    AVWeakReference *weakReference;
    AVWeakReference *weakReferenceToAssetWriter;
}

@end
