/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSString, NSArray;

@interface AVAudioSessionPortDescription : NSObject {
    void *_impl;
}

@property(readonly) NSString * UID;
@property(readonly) NSArray * channels;
@property(readonly) NSString * portName;
@property(readonly) NSString * portType;

+ (id)privateCreatePortDescriptionsArrayWithCFArray:(struct __CFArray { }*)arg1;
+ (id)privateCreateWithCFDictionaryRef:(struct __CFDictionary { }*)arg1;

- (id)UID;
- (id)channels;
- (void)dealloc;
- (id)description;
- (id)init;
- (id)portName;
- (id)portType;
- (struct PortDescriptionImpl { id x1; id x2; id x3; id x4; }*)privateGetImplementation;

@end
