/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicEntityVerticalLockupView : MusicEntityAbstractLockupView <MusicEntityContentDescriptorViewConfiguring> {
    <MusicEntityVerticalLockupViewDelegate> *_delegate;
}

@property (nonatomic, retain) MusicEntityViewContentDescriptor *contentDescriptor;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <MusicEntityVerticalLockupViewDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) <MusicEntityValueProviding> *entityValueProvider;
@property (readonly) unsigned int hash;
@property (readonly) Class superclass;

+ (float)maximumHeightForContentDescriptor:(id)arg1 width:(float)arg2 traitCollection:(id)arg3;

- (void).cxx_destruct;
- (void)_contentDescriptorDidChange:(id)arg1;
- (void)_handlePlayButtonTappedWithAction:(unsigned int)arg1;
- (BOOL)_shouldArtworkViewRespectHighlightProperty;
- (BOOL)_shouldEnableArtworkViewUserInteraction;
- (id)contentDescriptor;
- (id)delegate;
- (void)layoutSubviews;
- (void)setContentDescriptor:(id)arg1;
- (void)setDelegate:(id)arg1;

@end
