/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
 */

@interface MusicEntityPlaybackStatusController : NSObject <MusicPlaybackProgressScrubbing> {
    BOOL _alwaysLive;
    MPUContentItemIdentifierCollection *_currentContainerIdentifierCollection;
    MPUContentItemIdentifierCollection *_currentItemIdentifierCollection;
    NSHashTable *_observers;
    double _playbackCurrentTime;
    double _playbackCurrentTimeOriginatingTime;
    int _playbackDisplayState;
    double _playbackDuration;
    MusicPlaybackProgressScrubberController *_playbackProgressScrubberController;
    float _playbackRate;
    MPAVController *_player;
}

@property (getter=isAlwaysLive, nonatomic) BOOL alwaysLive;
@property (nonatomic, readonly) int currentScrubSpeed;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) double effectiveCurrentTime;
@property (readonly) unsigned int hash;
@property (nonatomic, readonly) MPAVController *player;
@property (nonatomic) float rate;
@property (nonatomic) <MusicPlaybackProgressScrubberDelegate> *scrubberDelegate;
@property (getter=isScrubbingEnabled, nonatomic) BOOL scrubbingEnabled;
@property (readonly) Class superclass;
@property (nonatomic) double totalDuration;

- (void).cxx_destruct;
- (void)_enumerateObserversUsingBlock:(id /* block */)arg1;
- (void)_feederContentItemIdentifierCollectionDidChangeNotification:(id)arg1;
- (void)_getContainerIdentifierCollection:(out id*)arg1 itemIdentifierCollection:(out id*)arg2 forItem:(id)arg3;
- (void)_itemContentItemIdentifierCollectionDidChangeNotification:(id)arg1;
- (id)_playbackStatusForPlaybackDisplayState:(int)arg1;
- (void)_playerContentsDidChangeNotification:(id)arg1;
- (void)_playerItemWillChangeNotification:(id)arg1;
- (void)_playerPlaybackStateDidChangeNotification:(id)arg1;
- (void)_sendPlaybackStatusDidChange;
- (BOOL)_setCurrentTime:(double)arg1;
- (void)_updateCurrentPlaybackIdentifierSet;
- (void)addPlaybackStatusObserver:(id)arg1;
- (void)cancelScrubbing;
- (int)currentScrubSpeed;
- (void)dealloc;
- (double)effectiveCurrentTime;
- (id)initWithPlayer:(id)arg1;
- (BOOL)isAlwaysLive;
- (BOOL)isScrubbingEnabled;
- (double)playbackCurrentTime;
- (id)playbackStatusForContainerIdentifierCollection:(id)arg1 itemIdentifierCollection:(id)arg2;
- (id)player;
- (float)rate;
- (void)removePlaybackStatusObserver:(id)arg1;
- (id)scrubberDelegate;
- (void)setAlwaysLive:(BOOL)arg1;
- (void)setCurrentTime:(double)arg1;
- (void)setRate:(float)arg1;
- (void)setScrubberDelegate:(id)arg1;
- (void)setScrubbingEnabled:(BOOL)arg1;
- (void)setTotalDuration:(double)arg1;
- (double)totalDuration;

@end
